const keyValuePairs = {
    "vite": "hayaku",
    "allons(-y)": "ikimashô",
    "j'ai compris": "wakarimashita",
    "où": "doko",
    "[destination]": "e",
    "là-bas": "asoko",
    "être chaud": "atsui",
    "être": "desu",
    "[accord]": "ne",
    "ah oui / ainsi": "sô",
    "un": "ichi",
    "deux": "ni",
    "leçon": "ka",
    "[question]": "ka",
    "-ième": "dai",
    "picasso": "pikaso",
    "exposition": "ten",
    "avoir-regardé": "mimashita",
    "regarder": "miru",
    "quoi": "nani",
    "[objet]": "o",
    "pas encore": "mada",
    "être bien": "ii",
    "[engagement]": "yo",
    "demain": "ashita",
    "je vais": "ikimasu",
    "aller": "iku",
    "(négation)": "sen",
    "bonjour (matin)": "ohayô gozaimasu",
    "pain": "pan",
    "je mange": "tabemasu",
    "manger": "taberu",
    "café": "kôhi",
    "je bois": "nomimasu",
    "boire": "nomu",
    "bière": "bîru",
    "petit-déjeuner": "chôsoku",
    "trois": "san",
    "quatre": "yon",
    "cinq": "go",
    "six": "roku",
    "sept": "shichi",
    "sept (2ème version)": "nana",
    "pomme": "ringo",
    "alors": "soredewa",
    "oeuf": "tamago",
    "douane": "zeikan",
    "appareil photo": "kamera",
    "je possède": "motte imasu",
    "posséder": "motsu",
    "oui": "hai",
    "[lieu]": "ni",
    "il se trouve": "arimasu",
    "trouver (se)": "aru",
    "valise": "toranku",
    "[relation]": "no",
    "intérieur": "naka",
    "[sujet]": "ga",
    "vêtement": "fuku",
    "et": "to",
    "livre": "hon",
    "cela": "sore",
    "seulement": "dake",
    "[familiarité] alcool / de l'alcool ?": "o sake",
    "alcool": "sake",
    "parfait": "kekko",
    "huit": "hachi",
    "neuf (chiffre)": "kyû",
    "dix": "jû",
    "onze": "jû ichi"
}