const keyValuePairs = {
    "à": "en",
    "à": "a",
    "à la mi...": "a mediados de...",
    "abandonner": "abandonar",
    "abonnement": "abono",
    "d'abord": "primero",
    "absolu": "absoluto",
    "absolument pas": "en absoluto",
    "absurdité": "disparate",
    "accepter": "aceptar",
    "accident": "accidente",
    "accompagner": "acompanar",
    "accomplir": "cumplir",
    "accord": "acuerdo",
    "d'accord": "vale",
    "d'accord": "de acuerdo",
    "d'accord (ok)": "ya",
    "d'accord (en accord avec)": "conforme",
    "accro (addict)": "adicto",
    "achat": "compra",
    "acheter": "comprar",
    "acteur": "actor",
    "activité": "actividad",
    "actrice": "actriz",
    "actuel": "actual",
    "actuellement": "actualmente",
    "addition": "cuenta",
    "adieu": "adios",
    "ado": "quinceanero",
    "adresse": "direccion",
    "aéroport": "aeropuerto",
    "affaire": "negocio",
    "affaire (bonne)": "ganga",
    "affection": "carino",
    "affectueux": "carinoso",
    "âge": "edad",
    "âgé (très)": "anciano",
    "âgé": "mayor",
    "agir (il s'agit)": "tratarse",
    "agneau": "cordero",
    "agréable": "agradable",
    "aide": "ayuda",
    "aider": "ayudar",
    "aïe": "ay",
    "aigle": "aguila",
    "ailleurs (d')": "por cierto",
    "aimable": "amable",
    "aimer": "amar",
    "aimer (d'amour)": "querer",
    "ainsi que": "asi como",
    "air": "aire",
    "airbag": "airbag",
    "aisance": "soltura",
    "ajouter": "anadir",
    "alcool": "alcohol",
    "allemand": "aleman",
    "aller (vêtement)": "quedar",
    "aller (convenir)": "sentar",
    "aller (s'en)": "irse",
    "aller (nom)": "ida",
    "aller (verbe)": "ir",
    "aller chercher": "ir por",
    "allez !": "aupa",
    "allonger (s')": "echarse",
    "allumer": "encender",
    "allumette": "cerilla",
    "alors": "entonces",
    "Alpes": "Alpes",
    "amateur (de qqch)": "aficionado",
    "ambiance": "ambiente",
    "âme": "alma",
    "amener": "llevar",
    "amer": "amargo",
    "Amérique": "America",
    "Amérique centrale": "Centroamerica",
    "Amérique latine": "Latinoamerica",
    "ami": "amigo",
    "amitié": "amistad",
    "amour": "amor",
    "amoureux": "enamorado",
    "ampoule": "bombilla",
    "amusant": "divertido",
    "amuser (s')": "divertirse",
    "an": "ano",
    "ancêtre": "antepasado",
    "anchois": "boqueron",
    "ancien (objet)": "antiguo",
    "andalou": "andaluz",
    "Andalousie": "Andalucia",
    "Andes": "Andes",
    "âne": "burro",
    "ange (petit)": "angelito",
    "anglais": "ingles",
    "angle (de rue)": "esquina",
    "Angleterre": "Inglaterra",
    "animal": "animal",
    "animal de compagnie": "mascota",
    "anniversaire": "cumpleanos",
    "annonce": "anuncio",
    "annuler": "cancelar",
    "Antiquité": "Antiguedad",
    "appareil": "aparato",
    "appareil photo": "camara",
    "appartement": "piso",
    "appartenir": "pertenecer",
    "appel": "llamada",
    "appeler": "llamar",
    "appétit (bon)": "que approveche",
    "appétit (bon)": "buen provecho",
    "apporter": "traer",
    "apprendre": "aprender",
    "apprendre": "enterarse",
    "apprendre (enseigner)": "ensenar",
    "approuver": "aprobar",
    "après": "despues",
    "après": "tras",
    "après-demain": "pasado manana",
    "après-midi": "tarde",
    "arbre": "arbol",
    "arène": "ruedo",
    "argent": "dinero",
    "argent (métal)": "plata",
    "argent de poche": "paga",
    "argentin": "argentino",
    "Argentine": "Argentina",
    "arobase": "arroba",
    "arracher": "sacar",
    "arrêter": "parar",
    "arrêter": "dejar",
    "arrière-grand-père": "bisabuelo",
    "arriver": "pasar",
    "arriver": "llegar",
    "arriver (a faire qqch)": "conseguir",
    "art": "arte",
    "artiste": "artista",
    "ascenseur": "ascensor",
    "aspect": "pinta",
    "assemblée": "junta",
    "asseoir (s')": "sentarse",
    "assez": "bastante",
    "assez (en avoir)": "estar harto",
    "assiette": "plato",
    "assis": "sentado",
    "associer": "asociar",
    "assorti": "a juego",
    "assurance": "seguro",
    "astronome": "astronomo",
    "asturien": "asturiano",
    "atchoum": "achis",
    "Atlantique": "Atlantico",
    "atrocité": "barbaridad",
    "attacher (ceinture)": "abrochar",
    "atteindre": "alcanzar",
    "attendre": "esperar",
    "attentif (être)": "estar pendiente",
    "attentif": "atento",
    "attention": "cuidado",
    "attention (nom, détail)": "detalle",
    "attention (faire)": "tener cuidado",
    "attique (dernier étage)": "atico",
    "attirer": "atraer",
    "attraper": "pillar",
    "attrister": "poner triste",
    "au": "al",
    "au revoir": "adios",
    "aube": "amanecer",
    "aucun": "ninguno",
    "aujourd'hui": "hoy",
    "aussi": "tambien",
    "aussi... que": "tan... como",
    "autant": "tanto",
    "auto-école": "autoescuela",
    "automne": "otono",
    "autoroute": "autopista",
    "autour de": "alrededor de",
    "autre": "otro",
    "autrement dit": "o sea",
    "autres (les)": "los demas",
    "avance (d')": "de antemano",
    "avant": "antes",
    "avant": "ante",
    "avant (vers l')": "adelante",
    "avant tout": "ante todo",
    "avantage": "ventaja",
    "avantager": "favorecer",
    "avant-hier": "anteayer",
    "avant-hier soir": "anteanoche",
    "avec": "con",
    "avec moi": "conmigo",
    "avec toi": "contigo",
    "avenir": "porvenir",
    "avenue": "avenida",
    "avérer (s')": "resultar",
    "aveugle": "ciego",
    "aviateur": "aviador",
    "avion": "avion",
    "avion (petit)": "avioneta",
    "avis (à mon)": "en mi opinion",
    "avocat": "abogado",
    "avocat (fruit)": "aguacate",
    "avoir": "tener",
    "avoir (âge)": "cumplir",
    "avoir (auxiliaire)": "haber",
    "avoir la tête qui tourne": "estar mareado",
    "avouer": "confesar",
    "avril": "abril",
    "aztèque": "azteca",
    "baby-sitter": "canguro",
    "bagage à main": "equipaje de mano",
    "bagages": "equipaje",
    "bague": "anillo",
    "baguette de pain": "barra de pan",
    "baigner (se)": "banarse",
    "bailler": "bostezar",
    "baiser (un)": "beso",
    "baisser": "bajar",
    "balai": "escoba",
    "balai serpillère": "fregona",
    "balayer": "barrer",
    "ballon": "balon",
    "balourd": "bruto",
    "banane": "platano",
    "bancaire": "bancario",
    "bande (gang)": "pandilla",
    "banlieue": "afueras",
    "bar": "bar",
    "barbecue": "barbacoa",
    "Barcelone": "Barcelona",
    "barre": "barra",
    "bas (en)": "abajo",
    "bas": "bajo",
    "base": "base",
    "basketball": "baloncesto",
    "baskets": "deportivas",
    "basque": "vasco",
    "bateau": "barco",
    "bâton": "palo",
    "batterie": "bateria",
    "bavarder": "charlar",
    "beau": "guapo",
    "beau": "precioso",
    "beaucoup": "mucho",
    "beau frère": "cunado",
    "beau père": "suegro",
    "beauté": "belleza",
    "belle famille": "familia politica",
    "belle fille": "nuera",
    "bénitier": "pila",
    "besoin de (avoir)": "necesitar",
    "bête (insecte)": "bicho",
    "bête (idiot)": "tonto",
    "bêtise": "tonteria",
    "beurre": "mantequilla",
    "bien (insistance)": "ya",
    "bien (adv)": "bien",
    "bien élevé": "educado",
    "bien sûr (clairement)": "claro",
    "bientôt": "pronto",
    "bientôt (à)": "hasta pronto",
    "bienvenu": "bienvenido",
    "bière ": "cerveza",
    "billet": "billete",
    "billet (pour un spectacle)": "entrada",
    "billet de loterie": "decimo",
    "bizarre": "raro",
    "blague": "broma",
    "blague (faire une)": "gastar una broma",
    "blague (histoire drôle)": "chiste",
    "blanc de volaille": "pechuga",
    "blanc": "blanco",
    "blé": "trigo",
    "bleu": "azul",
    "blond": "rubio",
    "blouson": "cazadora",
    "boeuf": "buey",
    "boeuf": "ternera",
    "boire": "beber",
    "boisson": "bebida",
    "boite": "caja",
    "boite aux lettres": "buzon",
    "boite de conserve": "lata",
    "bon (très bon au goût)": "riquisimo",
    "bon (nom) (allez)": "vale",
    "bon à rien (inutile)": "inutil",
    "bon marché": "barato",
    "bon": "buen",
    "bon": "bueno",
    "bon (goût)": "rico",
    "bondé": "a tope",
    "bonheur": "felicidad",
    "bord": "orilla",
    "bouche": "boca",
    "bouché": "atascado",
    "boucherie": "carniceria",
    "boudin": "morcilla",
    "bouger (se)": "moverse",
    "boulanger": "panadero",
    "boulangerie": "panaderia",
    "boulot (petit)": "trabajillo",
    "bourse (étude)": "beca",
    "au bout de": "al cabo de",
    "bout de bois": "palo",
    "bouteille": "botella",
    "brancher": "enchufar",
    "bras": "brazo",
    "Brésil": "Brasil",
    "bringue": "juerga",
    "briquet": "mechero",
    "briser": "partir",
    "briser": "romper",
    "brochette": "pincho",
    "brocoli": "brocoli",
    "brosse": "cepillo",
    "bru": "nuera",
    "bruit": "ruido",
    "brûler": "quemar",
    "brun": "moreno",
    "bruyant": "ruidoso",
    "bungalow": "bungalo",
    "bureau": "oficina",
    "bureau de tabac": "estanco",
    "but (sport)": "gol",
    "c'est-à-dire": "o sea",
    "ça": "eso",
    "cabine d'essayage": "probador",
    "cabinet (d'avocat)": "bufete",
    "cacao": "cacao",
    "caché": "oculto",
    "cacher": "esconder",
    "cadeau": "regalo",
    "cafard": "cucaracha",
    "café": "café",
    "cage": "jaula",
    "cahier": "cuaderno",
    "calamar": "calamar",
    "calmer (se)": "tranquilizarse",
    "camarade": "companero",
    "caméra": "camara",
    "campagne": "campo",
    "canard": "pato",
    "cancaner": "cotillear",
    "candidat": "candidato",
    "capable": "capaz",
    "capacité": "capacidad",
    "capitale": "capital",
    "capsule": "chapa",
    "carafe": "jarra",
    "Caraîbes": "el Caribe",
    "caresse": "caricia",
    "cargo": "carguero",
    "carnaval": "carnaval",
    "carotte": "zanahoria",
    "carré": "cuadrado",
    "carreau": "cuadro",
    "carrière": "carrera",
    "carte (bancaire)": "tarjeta",
    "carte (plan)": "mapa",
    "carte postale": "postal",
    "cas": "caso",
    "case": "casilla",
    "casser": "romper",
    "casser les pieds": "dar la lata",
    "cauchemar": "pesadilla",
    "cause": "causa",
    "ce (dém. neutre)": "lo",
    "ce/cet/cette": "este",
    "ce/cet/cette": "ese",
    "ceci": "esto",
    "ceinture": "cinturon",
    "cela dit": "ahora bien",
    "célèbre": "famoso",
    "célibataire": "soltero",
    "celui/celle/ceux/celles de": "el/la/los/las",
    "celui-là/celle-là": "aquel/aquella",
    "cent (pour)": "por ciento",
    "centime": "centimo",
    "central/du centre ville": "central",
    "centre": "centro",
    "cercueil": "ataud",
    "cerisier": "cerezo",
    "certain": "cierto",
    "ces": "esos",
    "chaise": "silla",
    "chaleur": "calor",
    "chambre à coucher": "dormitorio",
    "chance": "suerte",
    "changement": "cambio",
    "changer": "cambiar",
    "chanson": "cancion",
    "chanter": "cantar",
    "chanteur": "cantante",
    "chapeau": "sombrero",
    "chaque": "cada",
    "chargeur": "cargador",
    "charmant": "encantador",
    "charme": "encanto",
    "chat": "gato",
    "chatter": "chatear",
    "chaud": "caliente",
    "chauffage": "calefaccion",
    "chauffer": "calentar",
    "chausser (faire une pointure)": "calzar",
    "chaussette": "calcetin",
    "chaussure": "zapato",
    "chauve": "calvo",
    "chef": "jefe",
    "chemin": "camino",
    "chemin de fer": "ferrocarril",
    "chemise": "camisa",
    "chemisier": "blusa",
    "cher/chère (courrier formel)": "estimado",
    "cher/chère (prix)": "caro",
    "cher/chère (sentiments)": "querido",
    "chercher": "buscar",
    "chéri": "carino",
    "cheval": "caballo",
    "chevalerie": "caballeria",
    "cheveu": "pelo",
    "cheveux (chevelure)": "pelo",
    "chèvre": "cabra",
    "chewing-gum": "chicle",
    "chien": "perro",
    "Chili": "Chile",
    "Chine": "China",
    "chips": "patatas fritas (de bolsa)",
    "chirurgien": "cirujano",
    "chocolat": "chocolate",
    "choisir": "elegir",
    "choix": "eleccion",
    "chômage": "desempleo",
    "chômage": "paro",
    "chômeur": "desempleado",
    "chômeur": "parado",
    "chorizo": "chorizo",
    "chose": "cosa",
    "chouette (cool)": "chulo",
    "chrétien": "cristiano",
    "Christ": "Cristo",
    "churro": "churro",
    "ciel": "cielo",
    "cigare": "puro",
    "cigarette": "cigarrillo",
    "cimetière": "cementerio",
    "cinéma": "cine",
    "cinq": "cinco",
    "cinquième": "quinto",
    "circulation": "trafico",
    "citron": "limon",
    "civil": "civil",
    "civilisation": "civilizacion",
    "clair": "claro",
    "classe (année scolaire)": "curso",
    "classique": "clasico",
    "clavier": "teclado",
    "clé": "llave",
    "clé usb": "pen",
    "client": "cliente",
    "climatique": "climatico",
    "climatisation": "aire acondicionado",
    "cocher (une case)": "marcar",
    "cochon (salace)": "verde",
    "cocorico": "kikiriki",
    "code (examen du permis)": "teorico",
    "code (informatique)": "codigo",
    "coeur": "corazon",
    "coeur (par)": "de memoria",
    "cognac": "conac",
    "cohabiter": "convivir",
    "coin": "rincon",
    "col (de chemise)": "cuello",
    "collé (examen)": "suspenso",
    "coller": "pegar",
    "Colomb (Christophe)": "Colon",
    "colombe": "paloma",
    "combien": "cuanto",
    "combien de ": "cuanto(s)",
    "commande": "pedido",
    "commander": "pedir",
    "comme": "como",
    "comme (pareil que)": "igual que",
    "comme ça": "asi",
    "comme ci comme ça": "regular",
    "comme ci comme ça": "asi asi",
    "commencer": "empezar",
    "comment": "como",
    "commérage": "cotilleo",
    "commère": "cotilla",
    "commettre": "cometer",
    "compartiment": "compartimento",
    "comprendre": "entender",
    "comprimé (être)": "comprimido",
    "compte": "cuenta",
    "compte (en fin de)": "al fin y al cabo",
    "concierge": "portero",
    "conduire": "conducir",
    "conduite (examen du permis)": "practico",
    "confiance (avoir)": "fiarse",
    "confiance (faire)": "fiarse",
    "confiture": "mermelada",
    "confortable": "comodo",
    "congé (prendre)": "despedirse",
    "connaitre": "conocer",
    "connaitre (s'y)": "entender",
    "connecter": "conectar",
    "conquête": "conquista",
    "conquistador": "conquistador",
    "consacrer": "dedicar",
    "conseiller": "aconsejar",
    "consommer": "gastar",
    "construire": "construir",
    "conte": "cuento",
    "conteneur": "contenedor",
    "content": "contento",
    "contenter": "conformarse",
    "contenu": "contenido",
    "continent": "continente",
    "continuer": "seguir",
    "continuer": "continuar",
    "contrarié": "disgustado",
    "contrarier": "disgustar",
    "contrariété": "disgusto",
    "contravention": "multa",
    "contre (être)": "estar en contra",
    "convaincre": "convencer",
    "cool (c'est ... ici)": "hay buen rollo",
    "coordonnées": "datos",
    "copropriété": "comunidad",
    "coq": "gallo",
    "corbeau": "cuervo",
    "cordonnier": "zapatero",
    "corps": "cuerpo",
    "corrida": "corrida",
    "costume": "traje",
    "côté": "lado",
    "côte (de boeuf)": "chuleton",
    "côte (maritime)": "costa",
    "côte (pente)": "cuesta",
    "côtelette": "chuleta",
    "coton": "algodon",
    "cou": "cuello",
    "coucher (se)": "acostarse",
    "coucher (se)": "echarse",
    "coucher du soleil": "puesta del sol",
    "couci-couça": "ni fu ni fa",
    "coude": "codo",
    "coudre": "coser",
    "couleur": "color",
    "couloir": "pasillo",
    "coup": "golpe",
    "coup de feu": "tiro",
    "couper": "cortar",
    "coupes (jeu de cartes)": "copas",
    "couple": "pareja",
    "coupon": "cupon",
    "cour": "patio",
    "courage": "valentia",
    "courage": "animo",
    "courageux": "bravo",
    "courageux": "valiente",
    "courant (être au)": "enterarse",
    "courir": "correr",
    "courrier": "correo",
    "cours (cycle)": "curso",
    "cours (séance)": "clase",
    "courses": "compra",
    "cousin": "primo",
    "coût": "coste",
    "couteau": "cuchillo",
    "coûter": "costar",
    "coutume": "costumbre",
    "couvercle": "tapa",
    "couvrir": "tapar",
    "couvrir (se)": "abrigarse",
    "covoiturage": "coche compartido",
    "cow-boy": "vaquero",
    "craindre": "temer",
    "craint (ça)": "hay mal rollo",
    "cravate": "corbata",
    "crayon": "lapiz",
    "créatif": "creativo",
    "crever": "pinchar",
    "crier": "gritar",
    "crise (de nerfs, cardiaque)": "ataque",
    "cristal (verre en)": "copa de cristal",
    "croire": "creer",
    "croisement": "cruce",
    "croissant": "cruasan",
    "croix": "cruz",
    "croustillant": "crujiente",
    "croyant": "creyente",
    "cru": "crudo",
    "cui-cui": "pio pio",
    "cuillère": "cuchara",
    "cuir": "cuero",
    "cuire": "cocer",
    "cuisine": "cocina",
    "cuisinier": "cocinero",
    "cuisse": "muslo",
    "cul": "culo",
    "culot": "cara dura",
    "culture": "cultura",
    "culture (en agriculture)": "cultivo",
    "cure-dents": "palillo",
    "cursus": "carrera",
    "CV": "curriculum",
    "cybercafé": "ciber",
    "danger": "peligro",
    "dangereux": "peligroso",
    "dans": "en",
    "dans (+ durée)": "dentro de",
    "danser": "bailar",
    "date": "fecha",
    "davantage (plus)": "mas",
    "de": "de",
    "déboucher": "destapar",
    "debout": "de pie",
    "débrouiller": "desenvolverse",
    "début": "principio",
    "décembre": "diciembre",
    "décharger": "descargar",
    "décider": "decidir",
    "décision": "decision",
    "décollage": "despegue",
    "déconstruire": "deconstruir",
    "décontracté": "informal",
    "découvrir": "descubrir",
    "décrocher": "descolgar",
    "dedans": "dentro",
    "dedans": "adentro",
    "déduire": "deducir",
    "défaut": "defecto",
    "défendre": "defender",
    "dégoût": "asco",
    "dégoûté": "asqueado",
    "dégoûter": "dar asco",
    "déguisé": "disfrazado",
    "dehors": "fuera",
    "déjà": "ya",
    "délicieux": "exquisito",
    "demain": "manana",
    "demander": "pedir",
    "demander (poser une question)": "preguntar",
    "demander à voir": "preguntar por",
    "demander des nouvelles": "preguntar por",
    "démarrer": "arrancar",
    "déménager": "mudarse",
    "demi": "medio",
    "démoralisé": "desanimado",
    "dénoncer": "denunciar",
    "dent": "diente",
    "dent (molaire)": "muela",
    "dentifrice": "pasta de dientes",
    "départ (sortie)": "salida",
    "dépêcher (se)": "darse prisa",
    "dépenser": "gastar",
    "déposer": "echar",
    "déprimer": "deprimir",
    "depuis": "desde",
    "dernier": "ultimo",
    "dernier (passé)": "pasado",
    "derrière": "detras",
    "des": "unos",
    "dès que": "en cuanto",
    "désastre": "desastre",
    "descendre": "bajar",
    "descendre": "bajarse",
    "descente (dans le sens de la)": "cuesta abajo",
    "désert": "desierto",
    "désolé (être)": "sentir",
    "dessert": "postre",
    "dessin": "dibujo",
    "dessous": "debajo",
    "dessus/au-dessus": "encima",
    "destin": "destino",
    "destination": "destino",
    "détester": "detestar",
    "détruire": "destruir",
    "deux": "dos",
    "deux (les)": "ambos",
    "deux cents": "doscientos",
    "deuxième": "segundo",
    "deuxième classe": "turista",
    "devant": "ante",
    "devant": "delante",
    "développement": "desarrollo",
    "devenir": "ponerse",
    "deviner": "adivinar",
    "devoir": "tener que",
    "devoir": "deber",
    "devoirs (scolaires)": "tarea",
    "diable": "demonio",
    "différent": "diferente",
    "différent (distinct)": "distinto",
    "difficile": "dificil",
    "dimanche": "domingo",
    "dinde": "pavo",
    "dîner (repas)": "cena",
    "dîner (verbe)": "cenar",
    "dire": "decir",
    "discothèque": "discoteca",
    "discours": "discurso",
    "discret": "discreto",
    "discuter": "charlar",
    "disparaître": "desaparecer",
    "disponible": "disponible",
    "disposé": "dispuesto",
    "disputer": "renir",
    "disque": "disco",
    "distrayant": "entretenido",
    "distributeur automatique (de billets)": "cajero",
    "divorcé": "divorciado",
    "dix": "diez",
    "dixième": "decimo",
    "dizaine": "decena",
    "dock": "darsena",
    "doigt": "dedo",
    "donc": "de modo que",
    "donc (et)": "o sea",
    "donnée": "dato",
    "donner": "dar",
    "donner un coup de main": "echar una mano",
    "dont": "cuyo",
    "dorénavant": "de aqui en adelante",
    "dormir": "dormir",
    "dos": "espalda",
    "dos (sur le)": "boca arriba",
    "dossier": "carpeta",
    "douche": "ducha",
    "douche (prendre une)": "darse una ducha",
    "douleur": "dolor",
    "doux": "dulce",
    "douze/minuit": "doce",
    "draguer": "ligar",
    "dragueur": "ligon",
    "drap": "sabana",
    "drapeau": "bandera",
    "droit": "derecho",
    "droit/tout droit": "recto",
    "droite": "derecha",
    "droite (de) (politique)": "de derechas",
    "drôle": "gracioso",
    "drôlerie": "gracia",
    "dur": "duro",
    "eau": "agua",
    "échange": "cambio",
    "échange (en)": "a cambio",
    "échanger un mot": "cruzar palabra",
    "écharde": "astilla",
    "échec": "fracaso",
    "école": "escuela",
    "économiser": "ahorrar",
    "écouter": "escuchar",
    "écouter (ouir)": "oir",
    "écouter (faire cas)": "hacer caso",
    "écran": "pantalla",
    "écraser": "aplastar",
    "écraser (qqn en voiture)": "atropellar",
    "écrire": "escribir",
    "écriture": "escritura",
    "éducation": "educacion",
    "effacer": "borrar",
    "effectivement": "desde luego",
    "efficace": "eficaz",
    "effort": "esfuerzo",
    "égal": "igual",
    "église": "iglesia",
    "eh bien": "pues",
    "électroménager": "electrodomestico",
    "électronique": "electronico",
    "élégant": "elegante",
    "élevage": "ganaderia",
    "élever": "criar",
    "élire": "elegir",
    "elle": "ella",
    "embarquement": "embarque",
    "embarquer": "embarcar",
    "embêter (fatiguer)": "fastidiar",
    "embouteillage": "atasco",
    "embrasser (sens figuré)": "abarcar",
    "émission (de télé)": "programa",
    "emmener": "llevar",
    "empêcher": "impedir",
    "empereur": "emperador",
    "empire": "imperio",
    "emploi": "empleo",
    "emporter": "llevar",
    "emprunter": "tomar prestado",
    "en": "en",
    "encaisser": "cobrar",
    "enceinte": "embarazada",
    "enchanté": "encantado",
    "enchanter": "encantar",
    "encore": "todavia",
    "encore": "aun",
    "endormir (s')": "dormirse",
    "endroit": "lugar",
    "énerver (s')": "ponerse nervioso",
    "enfance": "infancia",
    "enfant": "nino",
    "enfer": "infierno",
    "enfermer": "encerrar",
    "enfin (finalement)": "finalmente",
    "enfin": "por fin",
    "enfin (résignation)": "en fin",
    "enlever (faire quitter)": "quitar",
    "ennemi": "enemigo",
    "ennuyer (s')": "aburrirse",
    "ennuyeux": "aburrido",
    "énormité": "barbaridad",
    "enquête": "encuesta",
    "enregistrer (bagage)": "facturar",
    "enregistrer (du son)": "grabar",
    "enrhumer (s')": "resfriarse",
    "ensemble": "juntos",
    "ensuite": "luego",
    "entendre (ouir)": "oir",
    "entendre (bien s')": "tener buen rollo",
    "enterrement": "entierro",
    "enthousiasme": "ilusion",
    "entier": "entero",
    "entièrement": "enteramente",
    "entouré": "rodeado",
    "entrée (au restaurant)": "primero",
    "entreprise": "empresa",
    "entretien": "entrevista",
    "enveloppe": "sobre",
    "envie": "ganas",
    "envie (faire)": "apetecer",
    "envie (faire)": "dar ganas",
    "envoyer": "mandar",
    "envoyer": "enviar",
    "épaule": "hombro",
    "épées (au jeu de cartes)": "espadas",
    "Epiphanie": "Reyes",
    "éplucher": "pelar",
    "époque": "epoca",
    "épouse": "esposa",
    "équipage": "tripulacion",
    "équipe": "equipo",
    "erreur": "error",
    "escalier": "escalera",
    "espagnol": "espanol",
    "espèces (en) (paiement)": "en efectivo",
    "espérance": "ilusion",
    "espérer": "esperar",
    "esprit": "mente",
    "essayer": "tratar",
    "essayer (tenter)": "intentar",
    "essayer (habillement)": "probarse",
    "essence": "gasolina",
    "estomac": "estomago",
    "et": "y",
    "étagère": "estanteria",
    "étape": "etapa",
    "état": "estado",
    "été": "verano",
    "éteindre": "apagar",
    "étendre (s')": "extenderse",
    "étendu": "extenso",
    "étiquette": "etiqueta",
    "étoile": "estrella",
    "étonner": "extranar",
    "étrange": "extrano",
    "étranger": "extranjero",
    "être (se trouver)": "estar",
    "être": "ser",
    "être": "estar",
    "être supporteur (d'une équipe de foot)": "ser del + equipo",
    "étroit": "estrecho",
    "études": "estudios",
    "études de commerce": "empresariales",
    "études universitaires": "carrera",
    "euh...": "ejem...",
    "euro": "euro",
    "européen": "europeo",
    "évaluation": "valoracion",
    "événement": "acontecimiento",
    "évier": "fregadero",
    "exact": "exacto",
    "exaspérer (s') (désespérer)": "desesperarse",
    "excellent": "optimo",
    "excuser": "disculpar",
    "exemple": "ejemplo",
    "exercice": "ejercicio",
    "exister": "existir",
    "exotique": "exotico",
    "expérience": "experiencia",
    "expliquer": "explicar",
    "exprès": "a proposito",
    "exprès": "adrede",
    "exprimer": "expresar",
    "extérieur (à l')": "fuera",
    "extraterrestre": "extraterrestre",
    "fabuleux": "fabuloso",
    "fac (université)": "universidad",
    "face à (faire)": "estar cara a...",
    "face à (faire)": "estar frente a...",
    "fâcher": "disgustar",
    "fâcher (se)": "enfadarse",
    "facile": "facil",
    "façon": "modo",
    "fade": "soso",
    "faible": "debil",
    "faim": "hambre",
    "faire": "hacer",
    "fait (de/en)": "de hecho",
    "famille": "familia",
    "farine": "harina",
    "fasciner": "fascinar",
    "fast-food": "hamburgueseria",
    "fatal": "fatal",
    "fatigue": "cansancio",
    "fatigué": "cansado",
    "faut (il)": "hay que",
    "faute": "culpa",
    "fauteuil": "sillon",
    "faux": "falso",
    "faveur": "favor",
    "félicitations": "enhorabuena",
    "femme": "mujer",
    "femme de ménage": "asistenta",
    "fenêtre": "ventana",
    "fenêtre (petite)": "ventanilla",
    "férié": "festivo",
    "ferme (campagne)": "granja",
    "fermer": "cerrar",
    "fermer l'oeil (dormir)": "pegar ojo",
    "festival": "festival",
    "fête": "fiesta",
    "feu": "fuego",
    "feu de joie": "hoguera",
    "feu de signalisation": "semaforo",
    "feuille": "hoja",
    "feutre (stylo)": "rotulador",
    "février": "febrero",
    "fiancé": "novio",
    "ficher (ne rien)": "no dar golpe",
    "fichier": "archivo",
    "fier": "orgulloso",
    "fierté": "orgullo",
    "film": "pelicula",
    "fils": "hijo",
    "fin": "fin",
    "fin": "final",
    "fin (fine)": "fino",
    "finir": "terminar",
    "finir": "acabar",
    "fixer rendez-vous": "quedar",
    "flamenco": "flamenco",
    "flaque": "charco",
    "fleur": "flor",
    "fleuve": "rio",
    "fois": "vez",
    "fois (il était une)": "erase una vez",
    "fois (signe de multiplication)": "por",
    "folie": "locura",
    "fonctionner": "funcionar",
    "fond": "fondo",
    "fond (à)": "a tope",
    "fonder": "fundar",
    "fontaine": "fuente",
    "football": "futbol",
    "footballeur": "futbolista",
    "force": "fuerza",
    "forêt": "bosque",
    "forme (en pleine)": "fenomenal",
    "formidable": "estupendo",
    "fort": "fuerte",
    "fou": "loco",
    "foule": "muchedumbre",
    "four": "horno",
    "fourchette": "tenedor",
    "fourré": "forrado",
    "fragile": "fragil",
    "frais": "fresco",
    "fraise": "fresa",
    "français": "frances",
    "frapper": "pegar",
    "frapper": "golpear",
    "fréquence": "frecuencia",
    "frère": "hermano",
    "friandises": "dulces",
    "frigo": "frigorifico",
    "frit": "frito",
    "frites (de pdt)": "patatas fritas",
    "froid": "frio",
    "froid (froide)": "frio",
    "fromage": "queso",
    "fromagerie": "queseria",
    "frontière": "frontera",
    "fruit (valeur abstraite)": "fruto",
    "fruit de mer": "marisco",
    "fruits": "fruta",
    "fruits secs": "frutos secos",
    "fumée": "humo",
    "fumer": "fumar",
    "gagner (aux jeux de hasard)": "tocar",
    "gai": "alegre",
    "gamin": "nino",
    "garage (atelier)": "taller",
    "garçon": "chico",
    "garçon": "muchacho",
    "garde": "guardia",
    "gare": "estacion",
    "garer (se)": "aparcar",
    "garniture": "guarnicion",
    "gâteau": "tarta",
    "gâteau": "bizcocho",
    "gâteau (petit)": "pastel",
    "gâteau sec": "galleta",
    "gauche (politique) (de)": "de izquierdas",
    "gauchiste": "izquierdista",
    "gaucho (argentin)": "gaucho",
    "gazeuse (eau)": "con gas",
    "géant": "gigante",
    "gel": "gel",
    "gelé": "helado",
    "gendre": "yerno",
    "gêner": "molestar",
    "genou": "rodilla",
    "genre": "tipo",
    "gens": "gente",
    "gentilhomme": "hidalgo",
    "glace (crème glacée)": "helado",
    "glace (eau gelée)": "hielo",
    "glacière": "nevera",
    "glaçon": "cubito",
    "gorge": "garganta",
    "goût": "gusto",
    "goût": "sabor",
    "goût (avoir un)": "saber",
    "goûter": "probar",
    "goûter (prendre un)": "merendar",
    "goûter (nom)": "merienda",
    "goutte": "gota",
    "grammatical": "gramatical",
    "grand (plus)": "maximo",
    "grand": "grande",
    "grand": "gran",
    "grand (taille)": "alto",
    "grand-père": "abuelo",
    "grands-parents": "abuelos",
    "gratuit": "gratis",
    "grill": "plancha",
    "grillé": "fundido",
    "griller (un feu de circulation)": "saltarse",
    "gris": "gris",
    "gronder": "renir",
    "gros lot (loterie)": "gordo",
    "gros mot": "palabrota",
    "gros": "gordo",
    "grossier": "malhablado",
    "grossir": "engordar",
    "guerre": "guerra",
    "guitare": "guitarra",
    "guitariste": "guitarrista",
    "ha !": "ja",
    "habillement": "ropa",
    "habiller (s')": "vestir",
    "habiller (s')": "vestirse",
    "habit(s)": "ropa",
    "habitude": "costumbre",
    "habitude (avoir l'habitude de)": "soler",
    "habituer (s')": "acostumbrarse",
    "haché (aliments)": "picado",
    "hamburger": "hamburguesa",
    "hand-ball": "balonmano",
    "haricot": "alubia",
    "haricot": "judia",
    "hasard": "casualidad",
    "hasard": "azar",
    "hâte": "prisa",
    "haut (en)": "arriba",
    "hauteur": "altura",
    "herbe": "hierba",
    "héros": "heroe",
    "heure": "hora",
    "heureusement": "menos mal",
    "heureux": "feliz",
    "hier": "ayer",
    "hispanophone": "hispanohablante",
    "hisser": "aupar",
    "histoire": "historia",
    "historien": "historiador",
    "hiver": "invierno",
    "homme": "hombre",
    "honnête": "honrado",
    "honte": "verguenza",
    "hôpital": "hospital",
    "horaire": "horario",
    "horreur": "terror",
    "horreur (faire)": "horrorizar",
    "hostie": "hostia",
    "hôte (celui qui reçoit)": "anfitrion",
    "hôte (l'invité)": "huesped",
    "hou là": "uf",
    "hublot (avion)": "ventanilla",
    "huile": "aceite",
    "huit": "ocho",
    "huître": "ostra",
    "humain": "humano",
    "humeur": "humor",
    "humeur (être d')": "estar para",
    "humide": "humedo",
    "hygiénique": "higienico",
    "ici": "aqui",
    "idéal": "ideal",
    "idée": "idea",
    "il y a": "hay",
    "illusion": "ilusion",
    "image": "imagen",
    "image collectionnable": "cromo",
    "imaginer": "imaginar",
    "immense": "inmenso",
    "immeuble": "edificio",
    "immigrant": "inmigrante",
    "immortaliser": "inmortalizar",
    "imperméable (trench)": "gabardina",
    "importance (sans)": "menudo",
    "important": "importante",
    "importe (n') lequel": "cualquier",
    "impression": "sensacion",
    "imprimé (livre/revue)": "impreso",
    "imprimer": "imprimir",
    "inca": "inca",
    "inconnu": "desconocido",
    "incroyable": "increible",
    "indépendant": "independiente",
    "Indien": "indio",
    "indigène": "indigena",
    "indispensable": "imprescindible",
    "infirmier": "enfermero",
    "informations personnelles": "datos",
    "informatique": "informatica",
    "informé (être)": "enterarse",
    "informer": "informar",
    "innocent": "inocente",
    "inoubliable": "inolvidable",
    "inquiet": "preocupado",
    "inscrire (s')": "apuntarse",
    "inscrire (s')": "matricularse",
    "insister": "insistir",
    "instituteur": "maestro",
    "insuffisant": "insuficiente",
    "intelligent": "inteligente",
    "intelligent": "listo",
    "interdire": "prohibir",
    "intéressant": "interesante",
    "intéresser": "interesar",
    "intérêt": "interes",
    "interphone": "telefonillo",
    "interrogation (examen)": "examen",
    "intime": "intimo",
    "introduire": "introducir",
    "inutile": "inutil",
    "inventer": "inventar",
    "investissement (sens figuré)": "dedicacion",
    "inviter": "invitar",
    "italien": "italiano",
    "itinéraire": "ruta",
    "jalousie (amoureuse)": "celos",
    "jalousie (envie)": "envidia",
    "jaloux (en amour)": "celoso",
    "jaloux (envieux)": "envidioso",
    "jaloux (être)": "tener envidia",
    "jamais": "nunca",
    "jambe": "pierna",
    "jambon": "jamon",
    "jambon blanc": "jamon de york",
    "jambon cru": "jamon serrano",
    "janvier": "enero",
    "japonais": "japones",
    "jaune": "amarillo",
    "je": "yo",
    "jean(s) (pantalon)": "vaqueros",
    "Jésus-Christ": "Cristo",
    "jetable": "desechable",
    "jeter": "echar",
    "jeu de cartes": "baraja",
    "jeu vidéo": "videojuego",
    "jeudi": "jueves",
    "jeune": "joven",
    "jeune (plus)": "menor",
    "jeunesse": "juventud",
    "joie": "ilusion",
    "joie de (se faire une)": "hacerle a uno ilusion",
    "joli": "bonito",
    "jouer": "jugar",
    "jouer les...": "ir de...",
    "jouet": "juguete",
    "joueur": "jugador",
    "jour": "dia",
    "journal": "periodico",
    "journal télévisé": "telediario",
    "jours (de nos)": "hoy en dia",
    "joyeux": "alegre",
    "judo": "judo",
    "juillet": "julio",
    "juin": "junio",
    "jumeau": "gemelo",
    "jungle": "selva",
    "juron": "taco",
    "jus": "zumo",
    "jusque/jusqu'à": "hasta",
    "juste": "justo",
    "juste (au)": "a cienca cierta",
    "justement": "precisamente",
    "kangourou": "canguro",
    "kiffant (être)": "molar",
    "kilomètre": "kilometro",
    "là": "ahi",
    "là-bas": "alli",
    "lagune": "laguna",
    "laid": "feo",
    "laine": "lana",
    "laisser": "dejar",
    "laisser en rade": "dejar tirado",
    "laisser sans voix": "dejar de piedra",
    "lait": "leche",
    "langue (idiome et organe)": "lengua",
    "langue (idiome)": "idioma",
    "large": "ancho",
    "lavabo": "lavabo",
    "lave-linge": "lavadora",
    "laver (par terre, les assiettes, etc.)": "fregar",
    "laver (se)": "lavarse",
    "laverie": "lavanderia",
    "le/l'": "el",
    "le (pronom pers compl)": "lo",
    "léger": "ligero",
    "légumes": "verdura",
    "lent": "lento",
    "lentement": "despacio",
    "lentille": "lenteja",
    "les": "las",
    "lessive": "detergente",
    "lettre (alphabet)": "letra",
    "lettre (courrier)": "carta",
    "leur": "les",
    "lever (se)": "levantarse",
    "lever tôt (se)": "madrugar",
    "lèvre": "labio",
    "levure": "levadura",
    "liberté": "libertad",
    "libraire": "librero",
    "librairie": "libreria",
    "libre": "libre",
    "licencier": "echar",
    "licencier": "despedir",
    "lieu de (au)": "en vez de",
    "lièvre": "liebre",
    "ligne": "linea",
    "lire": "leer",
    "liste": "lista",
    "lit": "cama",
    "lit double": "cama matrimonial",
    "littéraire": "literario",
    "littérature": "literatura",
    "livre": "libro",
    "livrer": "entregar",
    "livreur": "repartidor",
    "loge (d'immeuble)": "porteria",
    "loi": "ley",
    "loin": "lejos",
    "long": "largo",
    "loterie": "loteria",
    "louer": "alquilar",
    "loyer": "alquiler",
    "lui (pron perso compl indirect)": "le",
    "lui (pron perso sujet)": "el",
    "lumière": "luz",
    "lundi": "lunes",
    "lune": "luna",
    "lunettes": "gafas",
    "lutter": "luchar",
    "lycée": "instituto",
    "lycée (années de)": "bachillerato",
    "machine à laver": "lavadora",
    "machine à sous": "tragaperras",
    "madame": "senora",
    "mademoiselle": "senorita",
    "madrilène": "madrileno",
    "magasin": "tienda",
    "magasin de chaussures": "zapateria",
    "mai": "mayo",
    "maigre": "delgado",
    "maigrir": "adelgazar",
    "mail": "mail",
    "maillet": "mazo",
    "maillot de bain": "banador",
    "maintenant": "ahora",
    "maintenir (se)": "mantenerse",
    "maire": "alcalde",
    "mairie": "ayuntamiento",
    "mais": "pero",
    "mais": "sino",
    "maïs": "maiz",
    "maison": "casa",
    "maîtriser": "dominar",
    "majeur (en âge)": "mayor de edad",
    "mal": "mal",
    "mal (faire)": "doler",
    "mal (très)": "fatal",
    "mal (très)": "pesimamente",
    "mal au coeur (avoir) (voiture/avion...)": "marearse",
    "mal de mer (avoir)": "marearse",
    "malade": "enfermo",
    "maladroit": "torpe",
    "malgré": "a pesar de",
    "maman": "mama",
    "maman (terme affectueux)": "mami",
    "manche": "manga",
    "manger": "comer",
    "manière": "manera",
    "manière": "modo",
    "manque": "falta",
    "manquer": "faltar",
    "manteau": "abrigo",
    "marchander": "regatear",
    "marché": "mercado",
    "marché": "plaza",
    "marché (accord)": "trato",
    "marche (ça)": "marchando",
    "marcher": "andar",
    "marcher": "caminar",
    "mardi": "martes",
    "marée": "marea",
    "mari": "marido",
    "mariage (cérémonie)": "boda",
    "mariage": "matrimonio",
    "marié": "casado",
    "marier (se)": "casarse",
    "marquer": "marcar",
    "marron": "marron",
    "mars": "marzo",
    "match": "partido",
    "matelassier": "colchonero",
    "matière (d'enseignement)": "asignatura",
    "matin": "manana",
    "maure": "moro",
    "mauvais": "malo",
    "mauvais (très)": "pesimo",
    "maximum": "maximo",
    "maya": "maya",
    "me/m'": "me",
    "mec": "tio",
    "mécanicien": "mecanico",
    "médecin": "medico",
    "médecine": "medicina",
    "méditerranéen": "mediterraneo",
    "méga-concert": "megaconcierto",
    "meilleur": "mejor",
    "mêler": "mezclar",
    "membre de la famille": "familiar",
    "même (adj)": "mismo",
    "même (adv)": "hasta",
    "même (adv)": "incluso",
    "même (adv)": "aun",
    "même pas": "ni siquiera",
    "même si": "aunque",
    "mémoire": "memoria",
    "ménage": "limpieza",
    "mensonge": "mentira",
    "mention très bien": "sobresaliente",
    "mentir": "mentir",
    "menu (menue)": "menudo",
    "mer": "mar",
    "merci": "gracias",
    "merci beaucoup": "muchas gracias",
    "mercredi": "miercoles",
    "mériter": "merecer",
    "merveille": "maravilla",
    "merveilleusement": "divinamente",
    "message": "mensaje",
    "mesure que (à)": "conforme",
    "mettre": "poner",
    "mettre": "meter",
    "mettre (se)": "ponerse",
    "mettre à (se)": "echarse a",
    "mettre du temps": "tardar",
    "mettre longtemps": "tardar",
    "meuble": "mueble",
    "meuh": "mu",
    "Mexico": "Ciudad de Mexico",
    "Mexique": "Mexico",
    "miaou": "miau",
    "miel": "miel",
    "mien": "mio",
    "mieux": "mejor",
    "mignon": "mono",
    "milieu (au)": "en medio",
    "milk-shake": "batido",
    "mille": "mil",
    "millénaire": "milenario",
    "milliard": "mil millones",
    "millier": "millar",
    "milliers": "miles",
    "million": "millon",
    "mince": "menudo",
    "mineur (âge)": "menor de edad",
    "minijupe": "minifalda",
    "minuit": "medianoche",
    "minute": "minuto",
    "miroir": "espejo",
    "mi-saison": "entretiempo",
    "mode": "moda",
    "modèle": "modelo",
    "moderne": "moderno",
    "moi": "yo",
    "moi": "mi",
    "moins": "menos",
    "moins (au)": "por lo menos",
    "mois": "mes",
    "moitié": "mitad",
    "molaire": "muela",
    "mole (plat mexicain)": "mole",
    "moment": "rato",
    "mon/ma": "mi",
    "monde": "mundo",
    "mondialisation": "mundializacion",
    "monnaie (faire la)": "cambiar",
    "monnaie (le change)": "cambio",
    "monnaie (petites pièces)": "suelto",
    "monnaie (pièce)": "moneda",
    "monnaie (qu'on vous rend)": "vuelta",
    "monsieur": "caballero",
    "monsieur": "senor",
    "un Monsieur je sais tout": "un sabelotodo",
    "montagnard": "serrano",
    "montagne": "montana",
    "montagnes (chaîne de)": "sierra",
    "montée (dans le sens de la)": "cuesta arriba",
    "monter": "subir",
    "montre": "reloj",
    "montrer": "ensenar",
    "moquer (se)": "burlarse",
    "morceau": "trozo",
    "mort (la)": "muerte",
    "mort": "muerto",
    "morue": "bacalao",
    "mot": "palabra",
    "mot de passe": "contrasena",
    "motiver (se)": "animarse",
    "moto": "moto",
    "mou": "blando",
    "mouche": "mosca",
    "mouillé": "mojado",
    "mouiller": "mojar",
    "moule": "mejillon",
    "moulin": "molino",
    "mourir": "morir",
    "moustache": "bigote",
    "moustique": "mosquito",
    "moyen": "medio",
    "moyen": "manera",
    "Moyen Age": "Edad Media",
    "mur": "pared",
    "musée": "museo",
    "musique": "musica",
    "mystère": "misterio",
    "nager": "nadar",
    "nahuatl": "nahuatl",
    "naif": "inocente",
    "naitre": "nacer",
    "nana": "tia",
    "nature": "naturaleza",
    "naturel": "natural",
    "naviguer": "navegar",
    "ne... pas": "no",
    "nécessaire": "preciso",
    "nécessaire (être)": "hacer falta",
    "nécessaire (être)": "ser preciso",
    "neige": "nieve",
    "neiger": "nevar",
    "nerf": "nervio",
    "nettoyer": "limpiar",
    "neveu": "sobrino",
    "nez": "nariz",
    "Noël": "Navidad",
    "noir": "negro",
    "noix de coco": "coco",
    "nom": "nombre",
    "nom de baptême": "nombre de pila",
    "nom de famille": "apellido",
    "nomade": "nomada",
    "nombreux": "numeroso",
    "non": "no",
    "non plus": "tampoco",
    "nord": "norte",
    "normal": "normal",
    "note": "nota",
    "noter": "apuntar",
    "notre": "nuestro",
    "nougat": "turron",
    "nous (pron pers compl)": "nos",
    "nous (pron pers suj)": "nosotros",
    "nouveau": "nuevo",
    "nouvelle (nom)": "noticia",
    "novembre": "noviembre",
    "nu": "desnudo",
    "nuage": "nube",
    "nuit": "noche",
    "nuit de Noël": "Nochebuena",
    "nuit dernière (la)": "anoche",
    "nuit du jour de l'An": "Nochevieja",
    "numérique": "digital",
    "numéro": "numero",
    "obtenir": "conseguir",
    "obtenir": "sacar",
    "obtenir une note": "sacar una nota",
    "occasion": "oportunidad",
    "occasion": "ocasion",
    "occasion (d')": "de segunda mano",
    "octobre": "octubre",
    "odeur": "olor",
    "odorat": "olfato",
    "oeil": "ojo",
    "oeuf": "huevo",
    "oeuvre": "obra",
    "offenser": "ofender",
    "offert": "regalado",
    "offrir": "regalar",
    "offrir": "ofrecer",
    "oignon": "cebolla",
    "oiseau": "pajaro",
    "olive": "oliva",
    "olive": "aceituna",
    "olivier": "olivo",
    "ombre": "sombra",
    "omelette": "tortilla",
    "oncle": "tio",
    "or (métal)": "oro",
    "orange": "naranja",
    "ordinateur": "ordenador",
    "oreille": "oido",
    "oreille": "oreja",
    "oreiller": "almohada",
    "organiser": "montar",
    "orgueil": "orgullo",
    "orgueilleux": "orgulloso",
    "original": "original",
    "origine": "origen",
    "os": "hueso",
    "oser": "atreverse",
    "ou": "o",
    "où (interrogatif avec verbe de mouv)": "adonde",
    "où (interrogatif)": "donde",
    "où que (+ subjonctif)": "dondequiera que",
    "ouah (chien)": "guau",
    "oublier": "olvidar",
    "ouest": "oeste",
    "oui": "si",
    "ouïe (sens)": "oido",
    "ouvrable (jours)": "laborable",
    "ouvrir": "abrir",
    "page": "pagina",
    "pain": "pan",
    "pain (de mie)": "pan (de molde)",
    "paire": "par",
    "paix": "paz",
    "palais": "palacio",
    "pampa": "pampa",
    "panne": "averia",
    "panne (en)": "averiado",
    "panneau (de la circulation)": "senal",
    "pantalon": "pantalon",
    "papa": "papa",
    "papeterie": "papeleria",
    "papier": "papel",
    "papounet": "papi",
    "par": "por",
    "paradis": "paraiso",
    "paraître": "parecer",
    "parasol": "sombrilla",
    "parc": "parque",
    "parce que": "porque",
    "parcourir": "recorrer",
    "pardon": "perdon",
    "pardonner": "perdonar",
    "pareil": "igual",
    "pareil": "semejante",
    "parents": "padres",
    "paresse": "pereza",
    "paresseux": "vago",
    "parfait": "perfecto",
    "parfois": "de vez en cuando",
    "parfum (glaces)": "sabor",
    "parfum": "perfume",
    "parier": "apostar",
    "parking": "aparcamiento",
    "parler": "hablar",
    "part": "parte",
    "partager": "compartir",
    "participer": "participar",
    "particulier": "particular",
    "partie": "parte",
    "partie (faire)": "formar parte",
    "partir": "salir",
    "partir": "marcharse",
    "partisan": "partidario",
    "pas": "paso",
    "pas du tout": "en absoluto",
    "passer": "pasar",
    "passer (se)": "ocurrir",
    "passer l'été (pour les vacances)": "veranear",
    "passion": "pasion",
    "passionné": "apasionado",
    "patates sauce piquante": "patatas a la brava",
    "pâte": "pasta",
    "pâtes (les)": "la pasta",
    "patience": "paciencia",
    "pâtisserie": "reposteria",
    "patraque": "pachucho",
    "pauvre": "pobre",
    "paye": "paga",
    "payer": "pagar",
    "payer (faire)": "cobrar",
    "payer la tête (se)": "tomar el pelo",
    "pays": "pais",
    "paysage": "paisaje",
    "peau": "piel",
    "peigne": "peine",
    "peindre": "pintar",
    "peine (à)": "apenas",
    "peintre": "pintor",
    "pèlerin": "peregrino",
    "pendant": "durante",
    "pendant ce temps": "mientras tanto",
    "pendant que": "mientras",
    "pénible": "pesado",
    "pensée": "pensamiento",
    "penser": "pensar",
    "perdre": "perder",
    "père": "padre",
    "permettre": "permitir",
    "permis (de conduire)": "carné (de conducir)",
    "Pérou": "Peru",
    "personne (il n'y a)": "nadie",
    "personne (une)": "persona",
    "peser": "pesar",
    "petit café": "cafelito",
    "petit déjeuner": "desayuno",
    "petit": "pequeno",
    "petit (taille)": "bajo",
    "petite bouteille": "botellita",
    "petite réduction": "descuentito",
    "petit-fils": "nieto",
    "peu": "poco",
    "peu (de) (justesse)": "por poco",
    "peu (un petit)": "un poquito",
    "peuple": "pueblo",
    "peupler": "poblar",
    "peur": "miedo",
    "peur (faire)": "dar miedo",
    "peur (faire)": "asustar",
    "peut-être": "tal vez",
    "peut-être": "a lo mejor",
    "peut-être": "quizas",
    "peut-être": "puede ser",
    "peut-être": "acaso",
    "peut-être": "igual",
    "phénoménal": "fenomenal",
    "photo": "foto",
    "phrase": "frase",
    "pièce (habitation)": "habitacion",
    "pied": "pie",
    "pieds nus": "descalzo",
    "piège": "trampa",
    "pierre": "piedra",
    "pile (à l'heure)": "en punto",
    "pile ou face": "cara o cruz",
    "piment": "guindilla",
    "piquant": "picante",
    "piquer": "picar",
    "pire": "peor",
    "piscine": "piscina",
    "pistolet": "pistola",
    "pizza": "pizza",
    "pizzeria": "pizzeria",
    "place": "plaza",
    "place": "lugar",
    "plage": "playa",
    "plaindre (se)": "quejarse",
    "plaine": "llanura",
    "plainte (porter)": "poner una denuncia",
    "plaire": "gustar",
    "plaisanterie": "broma",
    "plaisir": "gusto",
    "plaisir": "placer",
    "plaisir (faire)": "hacer ilusion",
    "planche à voile": "windsurf",
    "planète": "planeta",
    "planter (pour un appareil)": "quedarse colgado",
    "planter": "plantar",
    "plat": "plato",
    "plat principal": "segundo",
    "plate (pour l'eau)": "sin gas",
    "plein aux as (être)": "estar forrado",
    "plein": "lleno",
    "plein": "pleno",
    "pleuvoir": "llover",
    "plombier": "fontanero",
    "pluie": "lluvia",
    "plus": "mas",
    "plus (en/de)": "encima",
    "plus (en outre)": "ademas",
    "plusieurs": "varios",
    "plutôt": "mas bien",
    "poche": "bolsillo",
    "pognon": "pasta",
    "poids": "peso",
    "poil": "pelo",
    "point": "punto",
    "point d'heure (à)": "a las tantas",
    "pointe": "punto",
    "pointure (chaussure)": "numero",
    "poire": "pera",
    "poireau": "puerro",
    "pois (vêtements)": "lunar",
    "pois chiche": "garbanzo",
    "poisson (à manger)": "pescado",
    "poisson (vivant)": "pez",
    "poissonnerie": "pescaderia",
    "poissonnier": "pescadero",
    "poli (aimable)": "educado",
    "police": "policia",
    "politique": "politica",
    "politique": "politico",
    "pollution": "contaminacion",
    "pomme": "manzana",
    "pomme de terre": "patata",
    "pompe à essence": "gasolinera",
    "pompier": "bombero",
    "pont": "puente",
    "pop-corn": "palomitas",
    "population": "poblacion",
    "porc": "cerdo",
    "port": "puerto",
    "portable (téléphone)": "movil",
    "portable (adj)": "portatil",
    "portefeuille": "cartera",
    "porter": "llevar",
    "poser": "poner",
    "poste": "puesto",
    "Poste (la)": "Correos",
    "poste (ordinateur)": "equipo",
    "pot-au-feu": "cocido",
    "poubelle": "basura",
    "poule": "gallina",
    "poulet": "pollo",
    "pour": "por",
    "pour": "para",
    "pour (être)": "estar a favor",
    "pourboire": "propina",
    "pourquoi": "por qué",
    "pourvu que": "siempre y cuando",
    "pourvu que...": "ojala",
    "pousser": "empujar",
    "poussière": "polvo",
    "pouvoir": "poder",
    "pratique": "practico",
    "pratiquement": "practicamente",
    "pratiquer": "practicar",
    "précolombien": "precolombino",
    "préférentiel": "preferente",
    "préférer": "preferir",
    "préhispanique": "prehispanico",
    "premier": "primero",
    "première classe": "preferente",
    "prendre": "tomar",
    "prendre": "coger",
    "prendre la tête": "comer el coco",
    "prendre le petit déjeuner": "desayunar",
    "prendre soin": "cuidar",
    "prénom": "nombre",
    "préparer (l'avenir)": "labrarse",
    "près": "cerca",
    "présentation": "presentacion",
    "président": "presidente",
    "presque": "casi",
    "presse": "prensa",
    "pressé (être)": "tener prisa",
    "presser (se)": "darse prisa",
    "presser (un fruit)": "exprimir",
    "pression (bière)": "cana",
    "prêt (être)": "listo",
    "prêter": "prestar",
    "prier": "rezar",
    "prier (qqn de faire qqch)": "rogar",
    "printemps": "primavera",
    "prison": "carcel",
    "prix": "precio",
    "prix (récompense)": "premio",
    "problème": "problema",
    "prochain": "proximo",
    "produire": "producir",
    "produit": "producto",
    "profession": "profesion",
    "profiter": "disfrutar",
    "profiter": "aprovechar",
    "projet (plan)": "plan",
    "promener": "pasear",
    "promener (se)": "pasear",
    "promotion": "oferta",
    "prophétie": "profecia",
    "propre": "limpio",
    "proverbe": "refran",
    "psychologique": "psicologico",
    "psychologue": "psicologo",
    "public": "publico",
    "pull(-over)": "jersey",
    "purée": "puré",
    "putain (interj vulg)": "hostia",
    "pyramide": "piramide",
    "Pyrénées": "Pirineos",
    "quai (gare ferroviaire)": "anden",
    "quai (gare routière, port)": "darsena",
    "qualifié": "capacitado",
    "quand": "cuando",
    "quand (interrogatif)": "cuando",
    "quart": "cuarto",
    "quartier": "barrio",
    "quatre": "cuatro",
    "quatre-vingts": "ochenta",
    "que (exclamatif)": "qué",
    "que (interrogatif)": "qué",
    "quel...!": "menudo...",
    "quel/quelle": "qué",
    "quel/quelle": "cual",
    "quelque": "alguno",
    "quelque": "algun",
    "quelque chose": "algo",
    "quelques": "unos",
    "quelques (et) (heure)": "y pico",
    "quelqu'un": "alguien",
    "qu'est-ce que": "qué",
    "question": "pregunta",
    "question (pas)": "ni hablar",
    "queue": "cola",
    "queue (faire la)": "hacer cola",
    "qui": "quien",
    "quinze": "quince",
    "quoi": "qué",
    "quotidien": "cotidiano",
    "quotidien": "diario",
    "quotidiennement": "a diario",
    "racine": "raiz",
    "raconter": "contar",
    "radio": "radio",
    "rafraichissement": "refresco",
    "raisin": "uva",
    "raison": "razon",
    "ramasser": "recoger",
    "ramener": "traer",
    "randonnée": "senderismo",
    "rapide": "rapido",
    "rappeler": "recordar",
    "rapport": "relacion",
    "raser (se)": "afeitarse",
    "rater (qqch)": "perderse (algo)",
    "rater (train/avion)": "perder",
    "rater (un examen)": "suspender",
    "ration": "racion",
    "ravissant": "precioso",
    "rayon (magasin)": "seccion",
    "rayure": "raya",
    "réalisateur": "director",
    "réaliser": "realizar",
    "réaliser (pour un voeu/rêve)": "cumplir",
    "recette": "receta",
    "recevoir": "recibir",
    "réchauffer": "calentar",
    "recherche": "busqueda",
    "recommander": "recomendar",
    "reconnaître": "reconocer",
    "reçu (examen)": "aprobado",
    "récupérer": "recuperar",
    "réduction": "descuento",
    "refléter": "reflejar",
    "refuge": "albergue",
    "refuser": "rechazar",
    "refuser": "negarse",
    "regarder": "ver",
    "regarder": "mirar",
    "régime": "dieta",
    "région": "region",
    "règle": "regla",
    "regretter": "arrepentirse",
    "regretter (manquer)": "echar de menos",
    "régulier": "regular",
    "réjouir": "alegrarse",
    "relation": "relacion",
    "religion": "religion",
    "remarquer": "notar",
    "remarquer": "fijarse",
    "remède": "remedio",
    "remercier": "agradecer",
    "remonter à": "remontarse a",
    "remplir": "llenar",
    "rencontrer": "encontrarse con",
    "rendez-vous": "cita",
    "rendre": "devolver",
    "rendre": "volver",
    "rendre (se)": "rendirse",
    "rendre compte (se)": "darse cuenta",
    "rendre malade": "poner enfermo",
    "rendre visite": "visitar",
    "rentrer (dans un vêtement)": "caber",
    "réparation": "arreglo",
    "réparer": "arreglar",
    "repas": "comida",
    "repasser (avec un fer)": "planchar",
    "repentir (se)": "arrepentirse",
    "répéter": "repetir",
    "répondre": "contestar",
    "reposer (se)": "descansar",
    "reproche": "reproche",
    "réseau (mobile)": "cobertura",
    "réseau": "red",
    "réservation": "reserva",
    "réserver": "reservar",
    "réservoir": "deposito",
    "résigner (se)": "conformarse",
    "résister": "resistir",
    "résolution": "proposito",
    "respecter": "respetar",
    "responsable (en charge de)": "encargado",
    "ressembler à": "parecer",
    "ressembler à": "salir a",
    "ressource": "recurso",
    "restaurant": "restaurante",
    "rester": "quedar",
    "rester": "quedarse",
    "retard": "retraso",
    "retouches": "arreglos",
    "retour": "vuelta",
    "retour": "regreso",
    "retraite (prendre sa)": "jubilarse",
    "retraité": "jubilado",
    "réussir (un examen)": "aprobar",
    "revanche (en)": "en cambio",
    "rêve": "sueno",
    "réveiller": "despertar",
    "réveiller (se)": "despertarse",
    "revendiquer": "reivindicar",
    "revenir": "volver",
    "revenir": "regresar",
    "rêver": "sonar",
    "réviser": "repasar",
    "rhume": "resfriado",
    "riche": "rico",
    "rien": "nada",
    "rire": "reir",
    "rire (pour)": "en broma",
    "rire (nom)": "risa",
    "rivière": "rio",
    "riz": "arroz",
    "robe": "vestido",
    "robinet": "grifo",
    "Rois Mages (Les)": "Reyes Magos",
    "romain": "romano",
    "roman": "novela",
    "romantique": "romantico",
    "rond": "redondo",
    "rosé": "rosado",
    "rôti": "asado",
    "roue": "rueda",
    "rouge": "rojo",
    "rouge": "colorado",
    "rouge (vin)": "tinto",
    "rouge à lèvres": "barra de labios",
    "rouge et blanc": "rojiblanco",
    "rougir": "ponerse colorado",
    "rouleau": "rollo",
    "rouler (qqn)": "dar gato por liebre",
    "route": "carretera",
    "roux": "pelirrojo",
    "rue": "calle",
    "russe": "ruso",
    "s'il te plaît": "por favor",
    "s'il te plaît": "porfa",
    "sabbatique": "sabatico",
    "sable": "arena",
    "sac": "bolsa",
    "sac (à main)": "bolso",
    "sac à dos": "mochila",
    "sachet": "bolsa",
    "sacrifice": "sacrificio",
    "saint": "santo",
    "saison (agricole, culturelle)": "temporada",
    "saison (de l'année)": "estacion",
    "salade": "ensalada",
    "salade (mensonge)": "rollo",
    "salade russe": "ensaladilla",
    "salaire": "sueldo",
    "sale": "sucio",
    "salé": "salado",
    "salir (se)": "ensuciarse",
    "salle": "sala",
    "salle à manger": "comedor",
    "salle de bain": "cuarto de bano",
    "saluer": "saludar",
    "salut (salutation informelle)": "hola",
    "samedi": "sabado",
    "sandwich": "bocadillo",
    "sandwich": "bocata",
    "sandwich au pain de mie": "sandwich",
    "sang": "sangre",
    "sans": "sin",
    "santé": "salud",
    "sardine": "sardina",
    "satisfait": "satisfecho",
    "sauce": "salsa",
    "saut": "salto",
    "sauter": "saltar",
    "sauvage": "salvaje",
    "sauver": "salvar",
    "saveur": "sabor",
    "savoir": "saber",
    "savon": "jabon",
    "science": "ciencia",
    "scolaire": "escolar",
    "sec": "seco",
    "second": "segundo",
    "seconde (unité de temps)": "segundo",
    "secouer": "sacudir",
    "secours": "socorro",
    "sécurité": "seguridad",
    "séduire": "seducir",
    "seigneurie": "merced",
    "séjour": "estancia",
    "sel": "sal",
    "selon": "segun",
    "semaine": "semana",
    "semblable": "semejante",
    "sembler": "parecer",
    "sens": "sentido",
    "sens dessus-dessous": "patas arriba",
    "sentir": "notar",
    "sentir (odeur)": "oler",
    "sentir (se)": "encontrarse",
    "sept": "siete",
    "sept cents": "setecientos",
    "septembre": "septiembre",
    "sérieusement": "en serio",
    "sérieux": "serio",
    "sérieux": "formal",
    "serpent": "serpiente",
    "serrer": "apretar",
    "serveur": "camarero",
    "service (rendre un)": "favor",
    "serviette de bain": "toalla",
    "serviette de table": "servilleta",
    "servir": "servir",
    "servir (s'occuper d'un client)": "atender",
    "seulement": "solo",
    "Séville": "Sevilla",
    "shampoing": "champu",
    "si (condition)": "si",
    "si (adv)": "tan",
    "siècle": "siglo",
    "siège": "asiento",
    "sien": "suyo",
    "signal": "senal",
    "signe": "sena",
    "signer": "firmar",
    "sincère": "sincero",
    "singe": "mono",
    "sirop": "jarabe",
    "site": "sitio",
    "situation": "situacion",
    "six": "seis",
    "skier": "esquiar",
    "slogan": "lema",
    "sobre": "sobrio",
    "social": "social",
    "société": "sociedad",
    "soeur": "hermana",
    "soif": "sed",
    "soigneux": "cuidadoso",
    "soir": "noche",
    "soixante-dix-neuf": "setenta y nueve",
    "sol": "suelo",
    "soldé": "rebajado",
    "soldes": "rebajas",
    "soleil": "sol",
    "solitude": "soledad",
    "solution": "solucion",
    "sombre": "oscuro",
    "sommeil": "sueno",
    "son (nom)": "sonido",
    "son (sa)": "su",
    "sonner": "sonar",
    "sono": "megafonia",
    "sorte": "modo",
    "sorte (de ... que)": "de modo que",
    "sortir (intrans)": "salir",
    "sortir (trans)": "sacar",
    "sortir avec (qqn)": "tener un rollo con",
    "sortir prendre un verre": "ir de copas",
    "sou": "perra",
    "sou": "duro",
    "soubressade": "sobrasada",
    "souci": "preocupacion",
    "soudain": "de pronto",
    "souffler": "soplar",
    "souffrance": "sufrimiento",
    "souffrir": "sufrir",
    "souhaiter": "desear",
    "souhaits (à tes)": "Salud",
    "soul": "borracho",
    "soupe moulinée": "puré",
    "sourd": "sordo",
    "sourire": "sonrisa",
    "sourire (verbe)": "sonreir",
    "souris": "raton",
    "sous-sol": "sotano",
    "souvenir (un)": "recuerdo",
    "souvenir (se)": "acordarse",
    "souvent": "a menudo",
    "spécialité": "especialidad",
    "splendide": "estupendo",
    "sport": "deporte",
    "sportif": "deportista",
    "sports collectifs": "deportes de equipo",
    "stade": "estadio",
    "station-service": "gasolinera",
    "statue": "estatua",
    "steak (filet)": "filete",
    "stockage": "almacenamiento",
    "stupéfait": "estupefacto",
    "style": "estilo",
    "stylo": "boli",
    "stylo": "boligrafo",
    "succès": "exito",
    "sucre": "azucar",
    "sucré": "dulce",
    "sud": "sur",
    "sud-est": "sureste",
    "Suède": "Suecia",
    "suédois": "sueco",
    "suffire": "bastar",
    "suffisant": "suficiente",
    "suggestion": "sugerencia",
    "suicide": "suicidio",
    "suivant": "siguiente",
    "suivre": "seguir",
    "super bien": "fenomenal",
    "superficie": "superficie",
    "supérieur": "superior",
    "supermarché": "super",
    "supporter": "aguantar",
    "supporter": "soportar",
    "supporteur": "hincha",
    "supposer": "suponer",
    "sur": "encima de",
    "sur": "sobre",
    "sûr (bien)": "por supuesto",
    "sûr (c'est)": "desde luego",
    "sûr": "seguro",
    "surface": "superficie",
    "surfer (internet)": "navegar",
    "surfer": "surfear",
    "surprendre": "sorprender",
    "surprise": "sorpresa",
    "surtout": "sobre todo",
    "surveiller": "vigilar",
    "survêtement": "chandal",
    "suspendre": "colgar",
    "suspens (en)": "pendiente",
    "sympathique": "simpatico",
    "sympathique (être)": "caer (bien)",
    "syndic": "administrador",
    "tabac": "tabaco",
    "table": "mesa",
    "tableau": "cuadro",
    "tâche": "tarea",
    "Tage": "Tajo",
    "taille (grandeur)": "tamano",
    "taille (tour de)": "cintura",
    "taille (vêtements)": "talla",
    "taire (se)": "callarse",
    "tambour": "tambor",
    "tango": "tango",
    "tant que": "mientras",
    "tapa": "tapa",
    "tapa (petite)": "tapita",
    "tapis": "alfombra",
    "tard": "tarde",
    "tarif": "tarifa",
    "tartine": "tostada",
    "tas": "monton",
    "tasse": "taza",
    "tatouage": "tatuaje",
    "taureau": "toro",
    "tauromachie": "tauromaquia",
    "te/t' (pron pers compl)": "te",
    "technologie": "tecnologia",
    "tee-shirt": "camiseta",
    "tel": "tal",
    "télécharger": "bajarse",
    "téléphone": "telefono",
    "téléphone (parler au)": "hablar por telefono",
    "téléphonique": "telefonico",
    "télé-poubelle": "telebasura",
    "télévision": "tele",
    "tellement": "tanto",
    "temps": "tiempo",
    "temps (avoir le)": "dar tiempo",
    "temps en temps (de)": "de vez en cuando",
    "tendresse": "carino",
    "tenir (spatial)": "caber",
    "tente": "tienda de campana",
    "terminer": "terminar",
    "terrasse": "terraza",
    "terre": "tierra",
    "tête": "cabeza",
    "tête (familier)": "coco",
    "texte": "texto",
    "thé": "té",
    "théâtre": "teatro",
    "théorique": "teorico",
    "thon": "atun",
    "ticket": "tique",
    "tiens/tiennes (les)": "tuyo(s)",
    "timbre": "sello",
    "tiret": "guion",
    "tiret du bas": "guion bajo",
    "toast (pour trinquer)": "brindis",
    "toi": "tu",
    "toilettes": "inodoro",
    "toilettes": "retrete",
    "toilettes": "vater",
    "toilettes (lieu public)": "servicio",
    "toit": "techo",
    "tomate": "tomate",
    "tomber": "caer",
    "tomber en panne": "estropearse",
    "ton/ta": "tu",
    "top (le)": "lo maximo",
    "torgnole/coup/baffe": "hostia",
    "tôt": "temprano",
    "totalement": "totalmente",
    "touche": "tecla",
    "toucher": "tocar",
    "toucher (salaire)": "cobrar",
    "toucher (sens)": "tacto",
    "toujours": "siempre",
    "tour (dans une queue)": "vez",
    "tour (édifice)": "torre",
    "tour (faire un)": "dar una vuelta",
    "tour (promenade)": "vuelta",
    "tour (trajet en boucle)": "vuelta",
    "touriste": "turista",
    "tourner": "girar",
    "tourner (un film)": "rodar",
    "tournure": "giro",
    "tout à l'heure (à)": "hasta luego",
    "tout autant": "otro tanto",
    "tout de suite": "enseguida",
    "tout/tous/toutes": "todo(s)",
    "tradition": "tradicion",
    "traduire": "traducir",
    "traînée (trace)": "rastro",
    "trajet": "trayecto",
    "tranche": "loncha",
    "tranquille": "tranquilo",
    "transformer": "convertir",
    "transpirer": "sudar",
    "transport": "transporte",
    "travail": "trabajo",
    "travailleur": "trabajador",
    "travailler": "trabajar",
    "traverser": "cruzar",
    "trente-huit": "treinta y ocho",
    "très": "muy",
    "très (plein de)": "la mar de",
    "très très (extrêmement)": "muchisimo",
    "trinquer": "brindar",
    "triste": "triste",
    "tristesse": "tristeza",
    "trois": "tres",
    "tromper": "enganar",
    "tromper (se)": "equivocarse",
    "trop": "demasiado",
    "trop de": "demasiado",
    "trouver": "encontrar",
    "trouver (se)": "quedar",
    "trouver (se)": "resultar",
    "tu": "tu",
    "tube": "tubo",
    "tuer": "matar",
    "turbulent": "revoltoso",
    "tutoyer": "hablar de tu",
    "type": "tio",
    "un/une": "uno",
    "uni": "liso",
    "université": "universidad",
    "utile": "util",
    "utilisateur": "usuario",
    "utiliser": "usar",
    "vacances": "vacaciones",
    "vache": "vaca",
    "vacher": "vaquero",
    "vague": "ola",
    "valise": "maleta",
    "vallée": "valle",
    "valoir": "valer",
    "vanille": "vainilla",
    "vanter (se)": "presumir",
    "variété": "variedad",
    "veau": "ternera lechal",
    "végétarien": "vegetariano",
    "veille": "vispera",
    "vélo": "bicicleta",
    "vendeur": "vendedor",
    "vendre": "vender",
    "vendredi": "viernes",
    "venir": "venir",
    "vent": "viento",
    "ventre (sur le)": "boca abajo",
    "véritable": "verdadero",
    "vérité": "verdad",
    "verre": "copa",
    "verre": "vaso",
    "verre (lunettes)": "cristal",
    "verre (matière)": "cristal",
    "vers (prép)": "hacia",
    "verser": "echar",
    "vert": "verde",
    "veste": "americana",
    "vêtement(s)": "ropa",
    "veuf": "viudo",
    "viande": "carne",
    "vide": "vacio",
    "vie": "vida",
    "viennoiserie (établissement)": "bolleria",
    "viennoiserie (individuelle)": "bollo",
    "vieux": "viejo",
    "vieux (plus)": "mayor",
    "vigne": "vinedo",
    "vignoble": "vinedo",
    "village": "pueblo",
    "ville": "ciudad",
    "ville (de)": "de vestir",
    "vin": "vino",
    "vin de Jerez": "fino",
    "vinaigre": "vinagre",
    "vingt et un": "veintiuno",
    "vingt-cinq": "veinticinco",
    "violent": "violento",
    "violet": "morado",
    "virtuel": "virtual",
    "virus": "virus",
    "visage": "cara",
    "visiter": "visitar",
    "vite": "rapido",
    "vite": "deprisa",
    "vite possible (le plus)": "cuanto antes",
    "vitesse": "velocidad",
    "vitre": "cristal",
    "vitrine": "escaparate",
    "vivre": "vivir",
    "voeu": "deseo",
    "voir": "ver",
    "voisin": "vecino",
    "voiture": "coche",
    "voix": "voz",
    "vol": "vuelo",
    "voler": "robar",
    "voleur": "ladron",
    "volonté": "voluntad",
    "volontiers (très)": "con mucho gusto",
    "votre": "su",
    "vôtre": "suyo",
    "vouloir": "querer",
    "vous (pron pers compl de politesse)": "les",
    "vous (pron pers compl de politesse singulier)": "les",
    "vous (pron pers compl)": "os",
    "vous (pron pers pl de politesse)": "ustedes",
    "vous (pron pers sing de politesse)": "usted",
    "vous (pron pers sujet)": "vosotros",
    "voyage": "viaje",
    "voyage de noces": "viaje de novios",
    "voyager": "viajar",
    "voyons": "a ver",
    "vrai": "verdadero",
    "vraiment": "de veras",
    "vraiment": "de verdad",
    "vue": "vista",
    "week-end": "fin de semana",
    "week-end": "finde",
    "western": "pelicula de vaqueros",
    "yaourt": "yogur",
    "youpi": "yuju",
    "zéro": "cero",
    "zone": "zona",
    "zoo": "zoologico",
}
