const wordsTradsAndLessons = [
    { "word": "vite", "trad": "hayaku", "lesson": "1" },
    { "word": "allons(-y)", "trad": "ikimashô", "lesson": "1" },
    { "word": "j'ai compris", "trad": "wakarimashita", "lesson": "1" },
    { "word": "où", "trad": "doko", "lesson": "1" },
    { "word": "[destination]", "trad": "e", "lesson": "1" },
    { "word": "là-bas", "trad": "asoko", "lesson": "1" },
    { "word": "être chaud", "trad": "atsui", "lesson": "1" },
    { "word": "être", "trad": "desu", "lesson": "1" },
    { "word": "[accord]", "trad": "ne", "lesson": "1" },
    { "word": "ah oui / ainsi", "trad": "sô", "lesson": "1" },
    { "word": "un", "trad": "ichi", "lesson": "1" },
    { "word": "deux", "trad": "ni", "lesson": "1" },
    { "word": "leçon", "trad": "ka", "lesson": "1" },
    { "word": "[question]", "trad": "ka", "lesson": "2" },
    { "word": "-ième", "trad": "dai", "lesson": "2" },
    { "word": "picasso", "trad": "pikaso", "lesson": "2" },
    { "word": "exposition", "trad": "ten", "lesson": "2" },
    { "word": "avoir-regardé", "trad": "mimashita", "lesson": "2" },
    { "word": "regarder", "trad": "miru", "lesson": "2" },
    { "word": "quoi", "trad": "nani", "lesson": "2" },
    { "word": "[objet]", "trad": "o", "lesson": "2" },
    { "word": "pas encore / jusqu'à", "trad": "mada", "lesson": "2" },
    { "word": "être bien", "trad": "ii", "lesson": "2" },
    { "word": "[engagement]", "trad": "yo", "lesson": "2" },
    { "word": "demain", "trad": "ashita", "lesson": "2" },
    { "word": "je vais (degré plus)", "trad": "ikimasu", "lesson": "2" },
    { "word": "aller", "trad": "iku", "lesson": "2" },
    { "word": "(négation)", "trad": "-masen", "lesson": "3" },
    { "word": "bonjour (matin)", "trad": "ohayô gozaimasu", "lesson": "3" },
    { "word": "pain", "trad": "pan", "lesson": "3" },
    { "word": "je mange", "trad": "tabemasu", "lesson": "3" },
    { "word": "manger", "trad": "taberu", "lesson": "3" },
    { "word": "café", "trad": "kôhi", "lesson": "3" },
    { "word": "je bois", "trad": "nomimasu", "lesson": "3" },
    { "word": "boire", "trad": "nomu", "lesson": "3" },
    { "word": "bière", "trad": "bîru", "lesson": "3" },
    { "word": "petit-déjeuner", "trad": "chôsoku", "lesson": "3" },
    { "word": "trois", "trad": "san", "lesson": "3" },
    { "word": "quatre", "trad": "yon", "lesson": "3" },
    { "word": "cinq", "trad": "go", "lesson": "3" },
    { "word": "six", "trad": "roku", "lesson": "3" },
    { "word": "sept", "trad": "shichi", "lesson": "3" },
    { "word": "sept (2ème version)", "trad": "nana", "lesson": "3" },
    { "word": "pomme", "trad": "ringo", "lesson": "3" },
    { "word": "alors", "trad": "soredewa / dewa", "lesson": "3" },
    { "word": "oeuf", "trad": "tamago", "lesson": "3" },
    { "word": "douane", "trad": "zeikan", "lesson": "4" },
    { "word": "appareil photo", "trad": "kamera", "lesson": "4" },
    { "word": "je possède", "trad": "motte imasu", "lesson": "4" },
    { "word": "posséder", "trad": "motsu", "lesson": "4" },
    { "word": "oui", "trad": "hai", "lesson": "4" },
    { "word": "[lieu]", "trad": "ni", "lesson": "4" },
    { "word": "il se trouve / il y a", "trad": "arimasu", "lesson": "4" },
    { "word": "trouver (se)", "trad": "aru", "lesson": "4" },
    { "word": "valise", "trad": "toranku", "lesson": "4" },
    { "word": "[relation]", "trad": "no", "lesson": "4" },
    { "word": "intérieur", "trad": "naka", "lesson": "4" },
    { "word": "[sujet]", "trad": "ga", "lesson": "4" },
    { "word": "vêtement", "trad": "fuku", "lesson": "4" },
    { "word": "et", "trad": "to", "lesson": "4" },
    { "word": "livre", "trad": "hon", "lesson": "4" },
    { "word": "cela", "trad": "sore", "lesson": "4" },
    { "word": "seulement", "trad": "dake", "lesson": "4" },
    { "word": "[familiarité] alcool / de l'alcool ?", "trad": "o sake", "lesson": "4" },
    { "word": "alcool", "trad": "sake", "lesson": "4" },
    { "word": "parfait", "trad": "kekkô", "lesson": "4" },
    { "word": "huit", "trad": "hachi", "lesson": "4" },
    { "word": "neuf (chiffre)", "trad": "kyû", "lesson": "4" },
    { "word": "dix", "trad": "jû", "lesson": "4" },
    { "word": "onze", "trad": "jû ichi", "lesson": "4" },
    { "word": "les courses", "trad": "kaimono", "lesson": "5" },
    { "word": "grand magasin", "trad": "depâto", "lesson": "5" },
    { "word": "ensemble", "trad": "issho", "lesson": "5" },
    { "word": "[adverbial]", "trad": "ni", "lesson": "5" },
    { "word": "j'achète", "trad": "kaimasu", "lesson": "5" },
    { "word": "acheter", "trad": "kau", "lesson": "5" },
    { "word": "chaussettes", "trad": "kutsushita", "lesson": "5" },
    { "word": "être arrivé", "trad": "tsukimashita", "lesson": "5" },
    { "word": "entrons", "trad": "hairimashô", "lesson": "5" },
    { "word": "ici", "trad": "koko", "lesson": "5" },
    { "word": "mais", "trad": "demo", "lesson": "5" },
    { "word": "cher", "trad": "takai", "lesson": "5" },
    { "word": "j'abandonne", "trad": "yamemasu", "lesson": "5" },
    { "word": "abandonner", "trad": "yameru", "lesson": "5" },
    { "word": "sky", "trad": "sukai", "lesson": "6" },
    { "word": "tree", "trad": "tsurî", "lesson": "6" },
    { "word": "tôkyô", "trad": "tôkyô", "lesson": "6" },
    { "word": "je connais", "trad": "shitte imasu", "lesson": "6" },
    { "word": "[à-partir-de]", "trad": "kara", "lesson": "6" },
    { "word": "comment", "trad": "dô", "lesson": "6" },
    { "word": "d'abord", "trad": "mazu", "lesson": "6" },
    { "word": "gare", "trad": "eki", "lesson": "6" },
    { "word": "[jusqu'à]", "trad": "made", "lesson": "6" },
    { "word": "bus", "trad": "basu", "lesson": "6" },
    { "word": "[moyen]", "trad": "de", "lesson": "6" },
    { "word": "être-proche", "trad": "chikai", "lesson": "6" },
    { "word": "là", "trad": "soko", "lesson": "6" },
    { "word": "train", "trad": "densha", "lesson": "6" },
    { "word": "ensuite", "trad": "sorekara", "lesson": "6" },
    { "word": "je marche", "trad": "arukimasu", "lesson": "6" },
    { "word": "aquarium", "trad": "suizokukan", "lesson": "6" },
    { "word": "intéressant / amusant", "trad": "omoshiroi", "lesson": "6" },
    { "word": "cadeau", "trad": "omiyage", "lesson": "6" },
    { "word": "magasin", "trad": "mise", "lesson": "6" },
    { "word": "aussi", "trad": "mo", "lesson": "6" },
    { "word": "beaucoup", "trad": "takusan", "lesson": "6" },
    { "word": "(affirmation)", "trad": "-masu", "lesson": "7" },
    { "word": "révision", "trad": "matome", "lesson": "7" },
    { "word": "(passé)", "trad": "-mashita", "lesson": "7" },
    { "word": "(invitation à soi ou à plusieurs)", "trad": "-mashô", "lesson": "7" },
    { "word": "je ne sais pas", "trad": "wakarimasen", "lesson": "7" },
    { "word": "cinéma", "trad": "eiga", "lesson": "8" },
    { "word": "hier", "trad": "kinô", "lesson": "8" },
    { "word": "avoir fait", "trad": "shimashita", "lesson": "8" },
    { "word": "ami", "trad": "tomodachi", "lesson": "8" },
    { "word": "être venu", "trad": "kimashita", "lesson": "8" },
    { "word": "être allé", "trad": "ikimashita", "lesson": "8" },
    { "word": "quoi", "trad": "nan (no)", "lesson": "8" },
    { "word": "Amérique", "trad": "amerika", "lesson": "8" },
    { "word": "Chaplin", "trad": "chappurin", "lesson": "8" },
    { "word": "moderne", "trad": "modan", "lesson": "8" },
    { "word": "temps", "trad": "taimuzu", "lesson": "8" },
    { "word": "était-intéressant", "trad": "omoshiro katta", "lesson": "8" },
    { "word": "lunettes", "trad": "megane", "lesson": "8" },
    { "word": "avoir-oublié", "trad": "wasuremashita", "lesson": "8" },
    { "word": "bien", "trad": "yoku", "lesson": "8" },
    { "word": "ne pas avoir été visible", "trad": "miemasen deshita", "lesson": "8" },
    { "word": "cuisine chinoise", "trad": "chûkaryôri", "lesson": "9" },
    { "word": "cuisine", "trad": "ryôri", "lesson": "9" },
    { "word": "restaurant", "trad": "ryôri", "lesson": "9" },
    { "word": "ce soir", "trad": "konban", "lesson": "9" },
    { "word": "ah !", "trad": "aa", "lesson": "9" },
    { "word": "très-aimé", "trad": "daisuki", "lesson": "9" },
    { "word": "moi", "trad": "watakushi", "lesson": "9" },
    { "word": "potage", "trad": "sûpu", "lesson": "9" },
    { "word": "viande", "trad": "niku", "lesson": "9" },
    { "word": "poisson", "trad": "sakana", "lesson": "9" },
    { "word": "prenons", "trad": "torimashô", "lesson": "9" },
    { "word": "[familiarité]", "trad": "o", "lesson": "9" },
    { "word": "baguettes", "trad": "hashi", "lesson": "9" },
    { "word": "non", "trad": "ii e", "lesson": "9" },
    { "word": "fourchette", "trad": "fôku", "lesson": "9" },
    { "word": "s'il te plaît", "trad": "onegai shimasu", "lesson": "9" },
    { "word": "s'il vous plaît", "trad": "kudasai", "lesson": "9" },
    { "word": "je-vous-prie / voici", "trad": "dôzo", "lesson": "9" },
    { "word": "merci", "trad": "arigatô", "lesson": "9" },
    { "word": "être bon", "trad": "oishii", "lesson": "9" },
    { "word": "très", "trad": "totemo", "lesson": "9" },
    { "word": "de-nouveau", "trad": "mata", "lesson": "9" },
    { "word": "japon", "trad": "nihon", "lesson": "10" },
    { "word": "télévision", "trad": "terebi", "lesson": "10" },
    { "word": "sumô", "trad": "sumô", "lesson": "10" },
    { "word": "saison", "trad": "shîzun", "lesson": "10" },
    { "word": "souvent", "trad": "yoku", "lesson": "10" },
    { "word": "quelquefois", "trad": "tokidoki", "lesson": "10" },
    { "word": "news (infos)", "trad": "nyûsu", "lesson": "10" },
    { "word": "série télé (drama)", "trad": "dorama", "lesson": "10" },
    { "word": "lequel-des-deux", "trad": "dochira", "lesson": "10" },
    { "word": "aimé", "trad": "suki", "lesson": "10" },
    { "word": "les-deux", "trad": "dochiramo", "lesson": "10" },
    { "word": "matin", "trad": "asa", "lesson": "11" },
    { "word": "à quelle heure", "trad": "nan ji ni", "lesson": "11" },
    { "word": "je me lève", "trad": "okimasu", "lesson": "11" },
    { "word": "heure", "trad": "ji", "lesson": "11" },
    { "word": "être-tard", "trad": "osoi", "lesson": "11" },
    { "word": "nuit / soir", "trad": "yoru", "lesson": "11" },
    { "word": "je dors / je me couche", "trad": "nemasu", "lesson": "11" },
    { "word": "aujourd'hui", "trad": "kyô", "lesson": "11" },
    { "word": "[renforcement]", "trad": "wa", "lesson": "11" },
    { "word": "[temps]", "trad": "ni", "lesson": "11" },
    { "word": "pleine-nuit", "trad": "yonaka", "lesson": "11" },
    { "word": "tout de même", "trad": "soredemo", "lesson": "11" },
    { "word": "après-midi", "trad": "gogo", "lesson": "11" },
    { "word": "bar", "trad": "bâ", "lesson": "11" },
    { "word": "je suis en train de travailler", "trad": "hataraite imasu", "lesson": "11" },
    { "word": "dans-ce-cas", "trad": "sorenara", "lesson": "11" },
    { "word": "terrible", "trad": "taihen", "lesson": "11" },
    { "word": "au café", "trad": "kissaten", "lesson": "12" },
    { "word": "bonjour (midi)", "trad": "konnichi wa", "lesson": "12" },
    { "word": "bonjour/entrez (serveur)", "trad": "irasshaimase", "lesson": "12" },
    { "word": "Mme/Mr", "trad": "san", "lesson": "12" },
    { "word": "[annonce]", "trad": "wa", "lesson": "12" },
    { "word": "[but]", "trad": "ni", "lesson": "12" },
    { "word": "moi (femme)", "trad": "watashi", "lesson": "12" },
    { "word": "bien", "trad": "jaa", "lesson": "12" },
    { "word": "gâteau", "trad": "kashi", "lesson": "12" },
    { "word": "vrai", "trad": "hontô", "lesson": "12" },
    { "word": "maintenant", "trad": "ima", "lesson": "12" },
    { "word": "régime", "trad": "daietto", "lesson": "12" },
    { "word": "quand", "trad": "itsu", "lesson": "12" },
    { "word": "rendez-vous", "trad": "yakusoku", "lesson": "13" },
    { "word": "ce-matin", "trad": "kesa", "lesson": "13" },
    { "word": "français", "trad": "furansu", "lesson": "13" },
    { "word": "être-humain", "trad": "jin / hito", "lesson": "13" },
    { "word": "devant / avant", "trad": "mae", "lesson": "13" },
    { "word": "heure", "trad": "jikan", "lesson": "13" },
    { "word": "avoir-attendu", "trad": "machimashita", "lesson": "13" },
    { "word": "extrêmement", "trad": "zuibun", "lesson": "13" },
    { "word": "être-fait", "trad": "shita", "lesson": "13" },
    { "word": "on-peut-penser-que", "trad": "deshô", "lesson": "13" },
    { "word": "être-ennuyé", "trad": "komarimashita", "lesson": "13" },
    { "word": "c'est impossible", "trad": "dekimasen", "lesson": "13" },
    { "word": "téléphone", "trad": "denwa", "lesson": "13" },
    { "word": "faire (degré plus)", "trad": "shimasu", "lesson": "13" },
    { "word": "[attribution]", "trad": "ni", "lesson": "13" },
    { "word": "savoir faire / être possible", "trad": "dekimasu", "lesson": "13" },
    { "word": "présentation", "trad": "shôkai", "lesson": "15" },
    { "word": "je m'appelle", "trad": "môchimasu", "lesson": "15" },
    { "word": "j'habite", "trad": "sunde imasu", "lesson": "15" },
    { "word": "an", "trad": "nen", "lesson": "15" },
    { "word": "mariage", "trad": "kekkon", "lesson": "15" },
    { "word": "enfant", "trad": "kodomo", "lesson": "15" },
    { "word": "deux-personnes", "trad": "futari", "lesson": "15" },
    { "word": "il existe", "trad": "imasu", "lesson": "15" },
    { "word": "fille", "trad": "onnanoko", "lesson": "15" },
    { "word": "garçon", "trad": "otokonoko", "lesson": "15" },
    { "word": "votre-fille (<20 ans)", "trad": "ojôsan", "lesson": "15" },
    { "word": "combien (how many)", "trad": "ikutsu", "lesson": "15" },
    { "word": "an (âge)", "trad": "sai", "lesson": "15" },
    { "word": "hein ?", "trad": "e ?", "lesson": "15" },
    { "word": "réalité", "trad": "jitsu", "lesson": "15" },
    { "word": "remariage", "trad": "saikon", "lesson": "15" },
    { "word": "votre-garçon (<15 ans)", "trad": "obotchan", "lesson": "15" },
    { "word": "dimanche", "trad": "nichiyôbi", "lesson": "16" },
    { "word": "temps", "trad": "tenki", "lesson": "16" },
    { "word": "pique-nique", "trad": "pikuniku", "lesson": "16" },
    { "word": "invitons", "trad": "sasoimashô", "lesson": "16" },
    { "word": "idée", "trad": "kangae", "lesson": "16" },
    { "word": "comment (respectueux)", "trad": "ikaga", "lesson": "16" },
    { "word": "j'emporte", "trad": "motte ikimasu", "lesson": "16" },
    { "word": "tenir", "trad": "motte", "lesson": "16" },
    { "word": "sandwich", "trad": "sandouitchi", "lesson": "16" },
    { "word": "sushi", "trad": "sushi", "lesson": "16" },
    { "word": "mandarine", "trad": "mikan", "lesson": "16" },
    { "word": "à l'intention de", "trad": "tame ni", "lesson": "16" },
    { "word": "jus de fruit", "trad": "jû su", "lesson": "16" },
    { "word": "[addition]", "trad": "ni", "lesson": "16" },
    { "word": "tout de suite", "trad": "sugu", "lesson": "16" },
    { "word": "faisons-fonctionner", "trad": "kakemashô", "lesson": "16" },
    { "word": "puce", "trad": "nomi", "lesson": "17" },
    { "word": "marché", "trad": "ichi", "lesson": "17" },
    { "word": "ce/cet/cette", "trad": "sono", "lesson": "17" },
    { "word": "boîte", "trad": "hako", "lesson": "17" },
    { "word": "droite", "trad": "migi", "lesson": "17" },
    { "word": "tasse", "trad": "chawan", "lesson": "17" },
    { "word": "combien (how much)", "trad": "ikura", "lesson": "17" },
    { "word": "celle-ci ?", "trad": "kore desu ka ?", "lesson": "17" },
    { "word": "gauche", "trad": "hidari", "lesson": "17" },
    { "word": "10 000", "trad": "man", "lesson": "17" },
    { "word": "yen", "trad": "en", "lesson": "17" },
    { "word": "pardon", "trad": "gomen nasai", "lesson": "17" },
    { "word": "1 000", "trad": "zen", "lesson": "17" },
    { "word": "un peu", "trad": "chotto", "lesson": "17" },
    { "word": "ancien", "trad": "furui", "lesson": "17" },
    { "word": "objet", "trad": "mono", "lesson": "17" },
    { "word": "Edo", "trad": "edo", "lesson": "17" },
    { "word": "époque", "trad": "jidai", "lesson": "17" },
    { "word": "ceci", "trad": "kore", "lesson": "17" },
    { "word": "merci beaucoup", "trad": "dômo arigatô gozaimasu", "lesson": "17" },
    { "word": "derrière", "trad": "ura", "lesson": "17" },
    { "word": "être-écrit", "trad": "kaite aru / katie arimasu", "lesson": "17" },
    { "word": "je me suis fait avoir / avoir été fait", "trad": "yarareta / yararemashita", "lesson": "17" },
    { "word": "librairie", "trad": "honya", "lesson": "18" },
    { "word": "Tolstoï", "trad": "torusutoi", "lesson": "18" },
    { "word": "guerre", "trad": "sensô", "lesson": "18" },
    { "word": "paix", "trad": "heiwa", "lesson": "18" },
    { "word": "un-petit-peu", "trad": "shôshô", "lesson": "18" },
    { "word": "attendez s'il vous plait", "trad": "omachi kudasai", "lesson": "18" },
    { "word": "montrez / montrerez", "trad": "misete kudasai", "lesson": "18" },
    { "word": "Chine", "trad": "chûgoku", "lesson": "18" },
    { "word": "ma-femme", "trad": "kanai", "lesson": "18" },
    { "word": "absent", "trad": "rusu", "lesson": "18" },
    { "word": "soi-même", "trad": "jibun", "lesson": "18" },
    { "word": "il-faut-faire", "trad": "shinakereba narimasen", "lesson": "18" },
    { "word": "ce", "trad": "kono", "lesson": "18" },
    { "word": "[politesse]", "trad": "o", "lesson": "18" },
    { "word": "conseil", "trad": "susume", "lesson": "18" },
    { "word": "fabriquer / utiliser", "trad": "tsukurimasu", "lesson": "18" },
    { "word": "facile", "trad": "kantan", "lesson": "18" },
    { "word": "pour chaque fois merci", "trad": "maido arigatô gozaimasu", "lesson": "18" },
    { "word": "concert", "trad": "konsâto", "lesson": "19" },
    { "word": "être-joli / ravissant", "trad": "utsukushii", "lesson": "19" },
    { "word": "qui", "trad": "dare", "lesson": "19" },
    { "word": "photo", "trad": "shashin", "lesson": "19" },
    { "word": "actrice", "trad": "joyû", "lesson": "19" },
    { "word": "ce n'est pas", "trad": "de wa arimasen", "lesson": "19" },
    { "word": "chanteuse", "trad": "kashu", "lesson": "19" },
    { "word": "de-quelle-sorte", "trad": "donna", "lesson": "19" },
    { "word": "chanson", "trad": "uta", "lesson": "19" },
    { "word": "je chante", "trad": "utaimasu", "lesson": "19" },
    { "word": "jazz", "trad": "jazu", "lesson": "19" },
    { "word": "cette-fois-ci", "trad": "kondo", "lesson": "19" },
    { "word": "samedi", "trad": "doyôbi", "lesson": "19" },
    { "word": "regrettable / dommage", "trad": "zannen", "lesson": "19" },
    { "word": "circonstance", "trad": "tsugô", "lesson": "19" },
    { "word": "être-mauvais", "trad": "warui", "lesson": "19" },
    { "word": "[plus-que]", "trad": "yori", "lesson": "19" },
    { "word": "beaucoup-plus", "trad": "motto", "lesson": "19" },
    { "word": "vraiment ?", "trad": "hontô", "lesson": "19" },
    { "word": "abandonnons", "trad": "yameyô", "lesson": "19" },
    { "word": "[réflexion]", "trad": "na/naa", "lesson": "19" },
    { "word": "déraisonnable", "trad": "muri", "lesson": "19" },
    { "word": "suivant", "trad": "tsugi", "lesson": "19" },
    { "word": "occasion", "trad": "kikai", "lesson": "19" },
    { "word": "absolument", "trad": "zehi", "lesson": "19" },
    { "word": "arrêt-de-fumer", "trad": "kinen", "lesson": "20" },
    { "word": "environ (lieu)", "trad": "hen", "lesson": "20" },
    { "word": "bureau-de-tabac", "trad": "tabakoya", "lesson": "20" },
    { "word": "loin", "trad": "tooi", "lesson": "20" },
    { "word": "ne-pas-être-loin", "trad": "tooku arimasen", "lesson": "20" },
    { "word": "voisin", "trad": "tonari", "lesson": "20" },
    { "word": "d'abord", "trad": "mazu", "lesson": "20" },
    { "word": "rue", "trad": "michi", "lesson": "20" },
    { "word": "tout-droit", "trad": "massugu", "lesson": "20" },
    { "word": "tourner", "trad": "magarimasu", "lesson": "20" },
    { "word": "coté-droit", "trad": "migigawa", "lesson": "20" },
    { "word": "être-grand", "trad": "ookii", "lesson": "20" },
    { "word": "de-celle-ci", "trad": "sono", "lesson": "20" },
    { "word": "je suis sauvé", "trad": "tasukarimashita", "lesson": "20" },
    { "word": "trois-jours", "trad": "mikka", "lesson": "20" },
    { "word": "avoir-fait", "trad": "shite imashita", "lesson": "20" },
    { "word": "ne-pas-s'être-poursuivi", "trad": "tsuzukimasen deshita", "lesson": "20" },
    { "word": "être-pénible / dur", "trad": "tsurai", "lesson": "20" },
    { "word": "moi (homme)", "trad": "boku", "lesson": "20" },
    { "word": "cigarette", "trad": "tabako", "lesson": "20" },
    { "word": "être-l'objet-du-désir-d'aspirer", "trad": "suitai", "lesson": "20" },
    { "word": "chinois", "trad": "kan", "lesson": "21" },
    { "word": "écriture", "trad": "ji", "lesson": "21" },
    { "word": "forme négative adj", "trad": "-ku arimasen", "lesson": "21" },
    { "word": "degré moins de -mashita", "trad": "-ta", "lesson": "21" },
    { "word": "degré moins de arimasu", "trad": "aru", "lesson": "21" },
    { "word": "degré moins de -mashô", "trad": "-yô", "lesson": "21" },
    { "word": "dessus", "trad": "ue", "lesson": "23" },
    { "word": "travail", "trad": "shigoto", "lesson": "23" },
    { "word": "votre-fils", "trad": "musuko san", "lesson": "23" },
    { "word": "bonne-santé (autre)", "trad": "o genki", "lesson": "23" },
    { "word": "bonne-santé (soi)", "trad": "genki", "lesson": "23" },
    { "word": "cette-année", "trad": "kotoshi", "lesson": "23" },
    { "word": "université", "trad": "daigaku", "lesson": "23" },
    { "word": "diplôme", "trad": "sotsugyô", "lesson": "23" },
    { "word": "université-de-Tôkyô", "trad": "tôdai", "lesson": "23" },
    { "word": "toutes-mes-félicitations", "trad": "omedetô gozaimasu", "lesson": "23" },
    { "word": "emploi", "trad": "tsutome", "lesson": "23" },
    { "word": "avril", "trad": "shigatsu", "lesson": "23" },
    { "word": "voiture", "trad": "jidôsha", "lesson": "23" },
    { "word": "lien", "trad": "kankei", "lesson": "23" },
    { "word": "entreprise", "trad": "kaisha", "lesson": "23" },
    { "word": "être-employé", "trad": "tsutomete imasu", "lesson": "23" },
    { "word": "être-bien (degré +)", "trad": "yoroshii", "lesson": "23" },
    { "word": "hospitalisation", "trad": "nyûin", "lesson": "23" },
    { "word": "mai", "trad": "gogatsu", "lesson": "23" },
    { "word": "circulation", "trad": "kôtsû", "lesson": "23" },
    { "word": "accident", "trad": "jiko", "lesson": "23" },
    { "word": "avoir-rencontré", "trad": "aimashita", "lesson": "23" },
    { "word": "c'est à plaindre", "trad": "okinodoku ni", "lesson": "23" },
    { "word": "ensuite", "trad": "sonogo", "lesson": "23" },
    { "word": "grâce-à-vous", "trad": "okagesama de", "lesson": "23" },
    { "word": "être-devenu", "trad": "narimashita", "lesson": "23" },
    { "word": "semaine-prochaine", "trad": "raishû", "lesson": "23" },
    { "word": "sortie-hôpital", "trad": "taiin", "lesson": "23" },
    { "word": "tranquillité", "trad": "anshin", "lesson": "23" },
    { "word": "bureau-de-poste", "trad": "yûbinkyoku", "lesson": "22" },
    { "word": "derrière", "trad": "ushiro", "lesson": "22" },
    { "word": "grèce", "trad": "girisha", "lesson": "22" },
    { "word": "par-avion", "trad": "kôkû", "lesson": "22" },
    { "word": "courrier", "trad": "yûbin", "lesson": "22" },
    { "word": "carte-postale", "trad": "hagaki", "lesson": "22" },
    { "word": "tarif", "trad": "ryôkin", "lesson": "22" },
    { "word": "angleterre", "trad": "igirisu", "lesson": "22" },
    { "word": "examiner/chercher", "trad": "shirabemasu", "lesson": "22" },
    { "word": "objet-plat", "trad": "mai", "lesson": "22" },
    { "word": "cent", "trad": "hyaku", "lesson": "22" },
    { "word": "appartement", "trad": "apâto", "lesson": "24" },
    { "word": "enfin", "trad": "yatto", "lesson": "24" },
    { "word": "avoir-été-trouvé", "trad": "mitsukari mashita", "lesson": "24" },
    { "word": "être-étroit", "trad": "semai", "lesson": "24" },
    { "word": "cependant/mais/malgré (moyen)", "trad": "keredomo/kedo", "lesson": "24" },
    { "word": "minute", "trad": "fun", "lesson": "24" },
    { "word": "en-marchant", "trad": "aruite", "lesson": "24" },
    { "word": "pratique", "trad": "benri", "lesson": "24" },
    { "word": "bruyant / agaçant", "trad": "urusai", "lesson": "24" },
    { "word": "bruit", "trad": "oto", "lesson": "24" },
    { "word": "absolument-pas", "trad": "zenzen", "lesson": "24" },
    { "word": "ne-pas-être-audible", "trad": "kikoemasen", "lesson": "24" },
    { "word": "école-maternelle", "trad": "yôchien", "lesson": "24" },
    { "word": "étage", "trad": "kai", "lesson": "24" },
    { "word": "vue", "trad": "nagame", "lesson": "24" },
    { "word": "cela / ah ça !", "trad": "sorega", "lesson": "24" },
    { "word": "juste", "trad": "chôdo", "lesson": "24" },
    { "word": "en-face", "trad": "mukai", "lesson": "24" },
    { "word": "bâtiment", "trad": "biru", "lesson": "24" },
    { "word": "se-dresser", "trad": "tatteimasu", "lesson": "24" },
    { "word": "rien", "trad": "nanimo", "lesson": "24" },
    { "word": "loyer", "trad": "yachin", "lesson": "24" },
    { "word": "esprit", "trad": "ki", "lesson": "24" },
    { "word": "entrer", "trad": "itte imasu", "lesson": "24" },
    { "word": "à-ce-point / tellement", "trad": "sorehodo", "lesson": "24" },
    { "word": "roman", "trad": "shôsetsu", "lesson": "25" },
    { "word": "écrire", "trad": "kaite imasu", "lesson": "25" },
    { "word": "policier (roman)", "trad": "suiri", "lesson": "25" },
    { "word": "publication", "trad": "shuppan", "lesson": "25" },
    { "word": "intention", "trad": "tsumori", "lesson": "25" },
    { "word": "faire (degré moyen)", "trad": "suru", "lesson": "25" },
    { "word": "histoire", "trad": "hanashi", "lesson": "25" },
    { "word": "héros", "trad": "shujinkô", "lesson": "25" },
    { "word": "mode", "trad": "fasshon", "lesson": "25" },
    { "word": "mannequin", "trad": "moderu", "lesson": "25" },
    { "word": "sans-le-savoir", "trad": "shiranaide", "lesson": "25" },
    { "word": "espion", "trad": "supai", "lesson": "25" },
    { "word": "[accompagnement]", "trad": "to", "lesson": "25" },
    { "word": "avoir l'air ...", "trad": "-sô", "lesson": "25" },
    { "word": "page", "trad": "pêji", "lesson": "25" },
    { "word": "à-peu-près", "trad": "gurai", "lesson": "25" },
    { "word": "devenir (degré plus)", "trad": "narimasu", "lesson": "25" },
    { "word": "[citation]", "trad": "to", "lesson": "25" },
    { "word": "penser", "trad": "omoimasu", "lesson": "25" },
    { "word": "être-long", "trad": "nagai", "lesson": "25" },
    { "word": "déjà", "trad": "mô", "lesson": "25" },
    { "word": "combien-à-peu-près", "trad": "donogurai", "lesson": "25" },
    { "word": "avoir-écrit", "trad": "kakimashita", "lesson": "25" },
    { "word": "écrire", "trad": "kaku", "lesson": "25" },
    { "word": "devenir (degré moyen)", "trad": "naru", "lesson": "25" },
    { "word": "aller (degré moyen)", "trad": "iku", "lesson": "26" },
    { "word": "année-prochaine", "trad": "rainen", "lesson": "26" },
    { "word": "printemps", "trad": "haru", "lesson": "26" },
    { "word": "mon-fils", "trad": "musuko", "lesson": "26" },
    { "word": "accompagner", "trad": "tsuru", "lesson": "26" },
    { "word": "cependant/mais (plus)", "trad": "shikashi", "lesson": "26" },
    { "word": "tourisme", "trad": "kankô", "lesson": "26" },
    { "word": "un-peu", "trad": "sukoshi", "lesson": "26" },
    { "word": "compagnon", "trad": "tomo", "lesson": "26" },
    { "word": "en-outre/de-plus", "trad": "soreni", "lesson": "26" },
    { "word": "temps-libre", "trad": "hima", "lesson": "26" },
    { "word": "être-sauvé", "trad": "tasukarimasu", "lesson": "26" },
    { "word": "absolument", "trad": "zehi", "lesson": "26" },
    { "word": "lundi", "trad": "getsuyôbi", "lesson": "26" },
    { "word": "soir", "trad": "ban", "lesson": "26" },
    { "word": "repas", "trad": "shokuji", "lesson": "26" },
    { "word": "langue japonaise", "trad": "nihongo", "lesson": "26" },
]