name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image and start services
        run: make build

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test

